package infra

import (
	"fmt"
	"path/filepath"
	"strings"
)

// exportReadme is the page somebody reads when they open this repository for the
// first time, which is usually months after it was made and without whoever ran
// the export in the room.
//
// It follows the shape of the lerian-cli README — badges, what is here, a quick
// start, then usage — because a client who has seen one Lerian repository should
// not have to learn a second layout to find the same facts. The content is this
// estate's own: its roots, its state keys, its environments.
func exportReadme(templatesRef string, plan ExportPlan) string {
	var readme strings.Builder

	writeReadmeHead(&readme, templatesRef)
	writeReadmeWhatIsHere(&readme, plan)
	writeReadmeFeatures(&readme)
	writeReadmeQuickStart(&readme, plan)
	writeReadmeUsage(&readme, plan)
	writeReadmeAdding(&readme, templatesRef)
	writeReadmeTroubleshooting(&readme, plan)

	return readme.String()
}

// writeReadmeHead is the title, the badges and the one paragraph that says what
// this repository is and who owns it now.
func writeReadmeHead(readme *strings.Builder, templatesRef string) {
	fmt.Fprintf(readme, "# Infrastructure for Lerian applications\n\n")

	fmt.Fprintf(readme, "[![Generated by](https://img.shields.io/badge/generated%%20by-%s-blue.svg)]"+
		"(https://github.com/LerianStudio/lerian-cli)\n", badgeText(Generator()))
	if templatesRef != "" {
		fmt.Fprintf(readme, "[![Templates](https://img.shields.io/badge/templates-%s-blue.svg)]"+
			"(https://github.com/LerianStudio/lerian-terraform-foundation)\n", badgeText(templatesRef))
	}
	fmt.Fprintf(readme, "[![Scope](https://img.shields.io/badge/scope-bootstrap%%20only-orange.svg)]"+
		"(#this-is-a-bootstrap-and-it-is-now-yours)\n")
	fmt.Fprintf(readme, "[![Terraform](https://img.shields.io/badge/Terraform-HCL-7B42BC?logo=terraform)]"+
		"(https://developer.hashicorp.com/terraform)\n\n")

	fmt.Fprintf(readme, "The AWS infrastructure the Lerian platform runs on: the network, the "+
		"cluster, the state backend, and whatever else was configured when this was "+
		"generated.\n\n")

	fmt.Fprintf(readme, "## This is a bootstrap, and it is now yours\n\n")
	fmt.Fprintf(readme, "Generated by **%s** (Lerian Studio)", Generator())
	if templatesRef != "" {
		fmt.Fprintf(readme, " from [lerian-terraform-foundation]"+
			"(https://github.com/LerianStudio/lerian-terraform-foundation) %s", templatesRef)
	}
	fmt.Fprintf(readme, ", once, as a starting point.\n\n")

	fmt.Fprintf(readme, "**It is not maintained by lerian-cli and will not be updated by it.** "+
		"The CLI wrote this repository and has no further relationship with it: it does not "+
		"read it, track it, or come back to change it. From here it is ordinary Terraform, "+
		"owned by whoever owns this repository — edit it, restructure it, put it in your own "+
		"pipeline.\n\n")
	fmt.Fprintf(readme, "Re-running the export writes a *new* repository; it does not merge into "+
		"this one. To pick up a later version of the templates, diff them against %s and apply "+
		"what you want by hand.\n\n", templatesRefOrThis(templatesRef))
}

// badgeText escapes a value for a shields.io path segment.
func badgeText(value string) string {
	return strings.NewReplacer(" ", "%20", "-", "--", "_", "__").Replace(value)
}

// writeReadmeWhatIsHere lists the roots the way the CLI README lists products:
// a heading each, and what it is for.
func writeReadmeWhatIsHere(readme *strings.Builder, plan ExportPlan) {
	fmt.Fprintf(readme, "## What is here\n\n")

	fmt.Fprintf(readme, "### Roots\n\n")
	fmt.Fprintf(readme, "Each is a Terraform root with its own state, applied in this order:\n\n")
	for _, root := range plan.Roots {
		path := filepath.ToSlash(plan.Target(root.Path))
		fmt.Fprintf(readme, "- **`%s`** — %s\n", path, describeRoot(path, root))
	}

	fmt.Fprintf(readme, "\n### Configuration\n\n")
	fmt.Fprintf(readme, "- **`%s`** — which AWS account each environment may touch\n",
		configPath(plan, "environments.conf"))
	fmt.Fprintf(readme, "- **`%s`** — where each environment keeps its state\n",
		configPath(plan, filepath.Join("backend", "<env>.hcl")))
	fmt.Fprintf(readme, "- **`envs/<env>.tfvars`** under each root — the sizing and the values "+
		"that were chosen\n")
	if len(plan.Modules) > 0 {
		names := make([]string, 0, len(plan.Modules))
		for _, module := range plan.Modules {
			names = append(names, "`"+filepath.Base(module)+"`")
		}
		fmt.Fprintf(readme, "- **`_modules/`** — shared modules the roots use: %s\n",
			strings.Join(names, ", "))
	}

	if plan.Base != "" {
		fmt.Fprintf(readme, "\nThe roots sit at the top level. In the templates they live under "+
			"`%s/`, which is the right name there and the wrong one here — this is not an "+
			"example of an estate, it is one. The directory was dropped from every path at "+
			"once, so each `source = \"../../_modules/...\"` still points where it did.\n\n",
			filepath.ToSlash(plan.Base))
	} else {
		fmt.Fprintf(readme, "\nThe directory layout is the templates' own, kept as it was so "+
			"every `source = \"../../_modules/...\"` still resolves.\n\n")
	}
}

// describeRoot says what a root is for, by the name the templates give it.
//
// Named rather than read out of the HCL: a description generated from resource
// counts says "17 resources", which is true and tells nobody anything. Anything
// unrecognized gets an honest placeholder instead of a guess.
func describeRoot(path string, root ExportedRoot) string {
	switch {
	case root.Bootstrap:
		return "the state bucket and lock table — runs on local state, because it creates " +
			"the backend the others use"
	case strings.HasSuffix(path, "/vpc"), path == "vpc":
		return "the network: subnets, routing, and the endpoints the cluster needs"
	case strings.HasSuffix(path, "/eks"), path == "eks":
		return "the Kubernetes cluster, its node groups and its addons"
	case strings.HasSuffix(path, "/route53"), path == "route53":
		return "the hosted zones and the records that point at this estate"
	case strings.HasSuffix(path, "/shared-services"):
		return "the services the products share"
	default:
		return "`" + root.StateKey + "`"
	}
}

// writeReadmeFeatures is what the Makefile gives, in the shape the CLI README
// uses for a product's features.
func writeReadmeFeatures(readme *strings.Builder) {
	fmt.Fprintf(readme, "## Core Features\n\n")
	fmt.Fprintf(readme, "- **One command per root** — `make plan eks dev`, with the backend "+
		"and the state key filled in for you\n")
	fmt.Fprintf(readme, "- **Groups** — `make plan infra-base dev` runs every root under it, "+
		"in order; `all` runs everything\n")
	fmt.Fprintf(readme, "- **Reverse on destroy** — a cluster cannot outlive the network it "+
		"sits in, so `destroy` walks the order backwards\n")
	fmt.Fprintf(readme, "- **Discovery** — a root is any directory with an `envs/` in it, so a "+
		"service added later needs no change to the Makefile\n")
	fmt.Fprintf(readme, "- **One confirmation** — `apply` and `destroy` ask before writing, "+
		"once per command, listing what they would touch\n")
	fmt.Fprintf(readme, "- **`make check`** — `fmt` and `validate` over every root, for your "+
		"own CI\n\n")
}

// writeReadmeQuickStart is the three commands somebody runs first.
func writeReadmeQuickStart(readme *strings.Builder, plan ExportPlan) {
	fmt.Fprintf(readme, "## Quick Start\n\n")

	fmt.Fprintf(readme, "### Prerequisites\n\n")
	fmt.Fprintf(readme, "- [Terraform](https://developer.hashicorp.com/terraform/downloads)\n")
	fmt.Fprintf(readme, "- `make`\n")
	fmt.Fprintf(readme, "- AWS credentials for the account the environment names in "+
		"`%s`\n\n", configPath(plan, "environments.conf"))

	fmt.Fprintf(readme, "```bash\n")
	fmt.Fprintf(readme, "# Who am I? This has to be the account the environment declares.\n")
	fmt.Fprintf(readme, "aws sts get-caller-identity\n\n")
	fmt.Fprintf(readme, "# What can I run this against?\n")
	fmt.Fprintf(readme, "make roots\n\n")
	fmt.Fprintf(readme, "# What would change? (writes nothing)\n")
	fmt.Fprintf(readme, "make plan %s dev\n", firstShort(plan))
	fmt.Fprintf(readme, "```\n\n")
}

// writeReadmeUsage is the reference: every target, then the same thing by hand.
func writeReadmeUsage(readme *strings.Builder, plan ExportPlan) {
	fmt.Fprintf(readme, "## Usage\n\n")

	fmt.Fprintf(readme, "### Make targets\n\n")
	fmt.Fprintf(readme, "| Command | What it does |\n|---|---|\n")
	fmt.Fprintf(readme, "| `make roots` | what can be run, and in what order |\n")
	fmt.Fprintf(readme, "| `make plan <root> [env]` | what would change — writes nothing |\n")
	fmt.Fprintf(readme, "| `make apply <root> [env]` | writes, after one confirmation |\n")
	fmt.Fprintf(readme, "| `make destroy <root> [env]` | removes, after one confirmation |\n")
	fmt.Fprintf(readme, "| `make output <root> [env]` | `terraform output` |\n")
	fmt.Fprintf(readme, "| `make test <root>` | `terraform test` |\n")
	fmt.Fprintf(readme, "| `make check` | `fmt` and `validate` over every root |\n")
	fmt.Fprintf(readme, "| `make help` | all of the above, from the terminal |\n\n")

	fmt.Fprintf(readme, "`<root>` is one root, or a directory holding several. "+
		"`[env]` defaults to `dev`.\n\n")
	// Aligned by measuring, not by counting spaces into a format string: the
	// names come from this estate and a column that fits one repository's roots
	// is ragged in the next.
	examples := [][2]string{
		{fmt.Sprintf("make plan %s dev", firstShort(plan)), "one root"},
	}
	if group := readmeGroup(plan); group != "" {
		examples = append(examples,
			[2]string{fmt.Sprintf("make plan %s dev", group), "every root under it, in order"})
	}
	examples = append(examples,
		[2]string{"make plan all dev", "every root there is"},
		[2]string{fmt.Sprintf("make %s-plan ENV=stg", firstShort(plan)), "the same, by target name"},
		[2]string{fmt.Sprintf("make plan ROOT=%s ENV=stg", firstPath(plan)), "and the long way"})

	width := 0
	for _, example := range examples {
		if len(example[0]) > width {
			width = len(example[0])
		}
	}

	fmt.Fprintf(readme, "```bash\n")
	for _, example := range examples {
		fmt.Fprintf(readme, "%-*s  # %s\n", width, example[0], example[1])
	}
	fmt.Fprintf(readme, "```\n\n")

	writeReadmeByHand(readme, plan)
}

// writeReadmeByHand is terraform without the Makefile, because a pipeline may
// not want one and because the arguments are worth seeing once.
func writeReadmeByHand(readme *strings.Builder, plan ExportPlan) {
	fmt.Fprintf(readme, "### Running Terraform directly\n\n")
	fmt.Fprintf(readme, "The Makefile is a convenience; this is what it runs. The `key=` is "+
		"derived from the root's own path and **cannot be guessed** — a wrong one does not "+
		"fail, it initializes an empty state and plans to create an estate that already "+
		"exists.\n\n")

	for _, root := range plan.Roots {
		path := filepath.ToSlash(plan.Target(root.Path))
		fmt.Fprintf(readme, "#### `%s`\n\n```bash\ncd %s\n", path, path)

		if root.Bootstrap {
			fmt.Fprintf(readme, "terraform init\n")
			fmt.Fprintf(readme, "terraform workspace select dev || terraform workspace new dev\n")
		} else {
			fmt.Fprintf(readme, "terraform init -reconfigure \\\n")
			fmt.Fprintf(readme, "  -backend-config=../../backend/dev.hcl \\\n")
			fmt.Fprintf(readme, "  -backend-config=\"key=%s\"\n", root.StateKey)
		}
		fmt.Fprintf(readme, "terraform plan -var-file=envs/dev.tfvars\n```\n\n")
	}

	fmt.Fprintf(readme, "`-reconfigure` is there because `.terraform/` remembers the last "+
		"backend it saw. Without it, a root initialized for one environment and then run for "+
		"another silently keeps the first one's bucket.\n\n")
}

// writeReadmeAdding is the shape a new service has to take, which is also the
// shape the Makefile looks for.
func writeReadmeAdding(readme *strings.Builder, templatesRef string) {
	fmt.Fprintf(readme, "## Adding a service\n\n")
	fmt.Fprintf(readme, "This repository holds the roots that were configured, not all of "+
		"them. To add one, copy its directory out of lerian-terraform-foundation at %s and "+
		"write its `envs/<env>.tfvars`.\n\n", templatesRefOrThis(templatesRef))
	fmt.Fprintf(readme, "Keep the shape and everything else follows: **a root is a directory "+
		"with an `envs/` in it, and its state key is its own path.** A service added that way "+
		"shows up in `make roots`, joins its group, and gets its own `<name>-plan` target, "+
		"with no change to the Makefile.\n\n")
	fmt.Fprintf(readme, "```bash\nmake roots      # it is in the list\nmake plan <name> dev\n```\n\n")
}

// writeReadmeTroubleshooting is the three things that look like breakage and are
// not. Each was hit while this was being verified against a real account.
func writeReadmeTroubleshooting(readme *strings.Builder, plan ExportPlan) {
	fmt.Fprintf(readme, "## Troubleshooting\n\n")

	fmt.Fprintf(readme, "### A plan proposes to create everything\n\n")
	fmt.Fprintf(readme, "Read it as \"this state is empty\" rather than \"this estate is "+
		"missing\". Either the environment really was torn down, or the plan is pointed "+
		"somewhere it should not be — the wrong account, or a `key=` that does not match the "+
		"one the state is stored at.\n\n")
	fmt.Fprintf(readme, "```bash\naws sts get-caller-identity\n"+
		"aws s3 ls s3://$(grep bucket %s | cut -d'\"' -f2)/ --recursive\n```\n\n",
		configPath(plan, filepath.Join("backend", "dev.hcl")))
	fmt.Fprintf(readme, "The second command lists the state objects that exist. If the `key=` "+
		"is not among them, nothing is wrong with your account — the plan was reading an "+
		"object that was never written.\n\n")

	if bootstrap := bootstrapPath(plan); bootstrap != "" {
		fmt.Fprintf(readme, "### `%s` wants to create a backend that exists\n\n", bootstrap)
		fmt.Fprintf(readme, "Its state is local and **did not travel with this repository**, "+
			"because state never belongs in one. It stayed on the machine the export was run "+
			"from, under `%s/terraform.tfstate.d/`. So a plan here starts from nothing and "+
			"proposes to create the backend again — which exists. That is the empty state "+
			"talking, not the truth about your account.\n\n", bootstrap)
		fmt.Fprintf(readme, "Three ways out, in the order they are usually right:\n\n")
		fmt.Fprintf(readme, "1. **Leave it alone.** The backend is created once in the life of "+
			"an environment; there is rarely anything to plan here again.\n")
		fmt.Fprintf(readme, "2. **Copy `%s/terraform.tfstate.d/`** across from the machine that "+
			"ran it, if you want to keep managing it from here.\n", bootstrap)
		fmt.Fprintf(readme, "3. **`terraform import`** each resource, if that machine is gone.\n\n")
		fmt.Fprintf(readme, "Do not apply it against an environment that already has a backend.\n\n")
	}

	if len(plan.Roots) > 1 {
		fmt.Fprintf(readme, "### `no matching EC2 VPC found`, and errors like it\n\n")
		fmt.Fprintf(readme, "A later root finds an earlier one's resources with data sources, "+
			"so planning it against an environment where the earlier one has not been applied "+
			"fails while reading them. That is the order talking, not a broken "+
			"configuration — `make plan <group> <env>` walks it for you.\n\n")
	}

	fmt.Fprintf(readme, "### `Error acquiring the state lock`\n\n")
	fmt.Fprintf(readme, "An interrupted run leaves its lock behind. Make sure nothing is still "+
		"running — another terminal, CI, a colleague — then release it:\n\n")
	fmt.Fprintf(readme, "```bash\nterraform -chdir=<root> force-unlock <the id in the error>\n```\n\n")
	fmt.Fprintf(readme, "Breaking a lock while a write is in flight is how one state gets two "+
		"writers.\n")
}

// bootstrapPath is the exported path of the root that runs on local state.
func bootstrapPath(plan ExportPlan) string {
	for _, root := range plan.Roots {
		if root.Bootstrap {
			return filepath.ToSlash(plan.Target(root.Path))
		}
	}
	return ""
}

// readmeGroup is a directory holding more than one root, for the worked example.
func readmeGroup(plan ExportPlan) string {
	holds := map[string]int{}
	for _, root := range plan.Roots {
		if parent := filepath.ToSlash(filepath.Dir(plan.Target(root.Path))); parent != "." {
			holds[parent]++
		}
	}
	for _, root := range plan.Roots {
		parent := filepath.ToSlash(filepath.Dir(plan.Target(root.Path)))
		if holds[parent] > 1 {
			return parent
		}
	}
	return ""
}

// templatesRefOrThis names the tag, or says the thing the tag stands for when
// there is no tag to name.
func templatesRefOrThis(templatesRef string) string {
	if templatesRef == "" {
		return "the version this was taken from"
	}
	return templatesRef
}

// configPath is where one of the configuration files landed, as the reader will
// find it. With nothing stripped these keep the templates' prefix, and naming
// them without it sends somebody to a path that is not there.
func configPath(plan ExportPlan, name string) string {
	if plan.Base == "" {
		for _, rel := range plan.Config {
			if strings.HasSuffix(filepath.ToSlash(rel), "/"+filepath.ToSlash(name)) {
				return filepath.ToSlash(rel)
			}
		}
		return filepath.ToSlash(filepath.Join("examples", "aws", name))
	}
	return filepath.ToSlash(name)
}
