package infra

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fakeGH writes a gh on PATH that says whatever the test needs it to say.
func fakeGH(t *testing.T, script string) GHCLI {
	t.Helper()
	path := filepath.Join(t.TempDir(), "gh")
	if err := os.WriteFile(path, []byte("#!/bin/sh\n"+script), 0o700); err != nil {
		t.Fatal(err)
	}
	return GHCLI{Binary: path}
}

// The login is read off the human output because gh has no machine-readable
// form of this one, which makes the parsing worth a test of its own: the whole
// offer turns on it, and a format drift reads as "not logged in" — sending
// somebody through a login they already have.
func TestTheLoggedInAccountIsRead(t *testing.T) {
	// On stderr, where gh writes it.
	gh := fakeGH(t, `cat >&2 <<'EOF'
github.com
  ✓ Logged in to github.com account octocat (keyring)
  - Active account: true
EOF
exit 0`)

	account, loggedIn := gh.GHStatus(context.Background())
	if !loggedIn {
		t.Fatal("a successful gh auth status was read as logged out")
	}
	if account.Login != "octocat" || account.Host != "github.com" {
		t.Errorf("read %+v, want octocat at github.com", account)
	}
	if account.String() != "octocat" {
		t.Errorf("printed %q — github.com is the default and does not need saying", account)
	}
}

// An enterprise host is part of the answer: two accounts of the same name on
// different hosts are different people.
func TestAnotherHostIsNamed(t *testing.T) {
	gh := fakeGH(t, `echo "✓ Logged in to github.acme.example account octocat (keyring)" >&2; exit 0`)

	account, _ := gh.GHStatus(context.Background())
	if got := account.String(); got != "octocat at github.acme.example" {
		t.Errorf("printed %q, want the host named", got)
	}
}

// A non-zero exit is how gh says nobody is logged in. Not an error here: that is
// the question being asked.
func TestNoLoginIsAnAnswerNotAFailure(t *testing.T) {
	gh := fakeGH(t, `echo "You are not logged into any GitHub hosts." >&2; exit 1`)

	account, loggedIn := gh.GHStatus(context.Background())
	if loggedIn {
		t.Error("a failed gh auth status was read as a login")
	}
	if account.String() != "not logged in" {
		t.Errorf("printed %q", account)
	}
}

// Exit zero with nothing recognizable means gh is logged in to something this
// cannot name. Usable is the honest answer: the other one costs somebody a login
// they already have.
func TestAnUnreadableStatusIsStillALogin(t *testing.T) {
	gh := fakeGH(t, `echo "something new"; exit 0`)

	if _, loggedIn := gh.GHStatus(context.Background()); !loggedIn {
		t.Error("a successful status was read as logged out because the wording changed")
	}
}

// The name reaches a command line, and the only way a value there turns into a
// flag is by starting with a dash.
func TestNamesArgvWouldMisreadAreRefused(t *testing.T) {
	for _, name := range []string{"", "   ", "--private", "-x", "my repo", "a/b/c"} {
		if err := (GHRepo{Name: name}).validate(); err == nil {
			t.Errorf("%q was accepted", name)
		}
	}
	for _, name := range []string{"infrastructure", "lerian/infrastructure", "infra-2026"} {
		if err := (GHRepo{Name: name}).validate(); err != nil {
			t.Errorf("%q was refused: %v", name, err)
		}
	}
}

// What gh is asked to do, exactly. Visibility is the argument that cannot be
// undone by deleting a directory, and --source/--push are what make this one
// command instead of three.
func TestTheCreateIsPrivateAndPushesFromTheExport(t *testing.T) {
	recorded := filepath.Join(t.TempDir(), "argv")
	gh := fakeGH(t, `printf '%s\n' "$@" > `+recorded+`
echo "https://github.com/octocat/infrastructure"
exit 0`)

	dir := t.TempDir()
	url, err := gh.CreateRepository(context.Background(), dir,
		GHRepo{
			Name:    "infrastructure",
			Private: true,
			// A repository called "infrastructure" with no description is one
			// somebody has to open to find out what it is.
			Description: "Terraform infrastructure, generated by lerian-cli",
		})
	if err != nil {
		t.Fatal(err)
	}
	if url != "https://github.com/octocat/infrastructure" {
		t.Errorf("read the url as %q", url)
	}

	argv, err := os.ReadFile(recorded)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"repo", "create", "infrastructure", "--private", "--source", "--push",
		"--description", "Terraform infrastructure, generated by lerian-cli"} {
		if !strings.Contains(string(argv), want) {
			t.Errorf("gh was not given %q:\n%s", want, argv)
		}
	}
	if strings.Contains(string(argv), "--public") {
		t.Errorf("a private repository was created public:\n%s", argv)
	}
}

// And public when that is what was chosen — the two must not collapse into one.
func TestPublicIsPassedWhenAskedFor(t *testing.T) {
	recorded := filepath.Join(t.TempDir(), "argv")
	gh := fakeGH(t, `printf '%s\n' "$@" > `+recorded+`; exit 0`)

	if _, err := gh.CreateRepository(context.Background(), t.TempDir(),
		GHRepo{Name: "infrastructure"}); err != nil {
		t.Fatal(err)
	}
	argv, err := os.ReadFile(recorded)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(argv), "--public") || strings.Contains(string(argv), "--private") {
		t.Errorf("the visibility was not the one chosen:\n%s", argv)
	}
}

// gh says why it failed on stderr, and an exit status alone is not a diagnosis:
// "name already exists" and "no permission in that org" are different problems
// with different answers.
func TestWhatGHSaidSurvivesTheFailure(t *testing.T) {
	gh := fakeGH(t, `echo "GraphQL: Name already exists on this account" >&2; exit 1`)

	_, err := gh.CreateRepository(context.Background(), t.TempDir(), GHRepo{Name: "taken"})
	if err == nil {
		t.Fatal("a failed create reported success")
	}
	if !strings.Contains(err.Error(), "Name already exists") {
		t.Errorf("the reason was dropped: %v", err)
	}
}

// Which account is active decides where a created repository lands, and it is
// marked on a line of its own. Read rather than assumed from the order: gh
// prints the active one first today, and "today" is not a guarantee worth
// resting a repository's owner on.
func TestTheActiveAccountIsReadNotAssumedFromTheOrder(t *testing.T) {
	gh := fakeGH(t, `cat >&2 <<'EOF'
github.com
  ✓ Logged in to github.com account robot (keyring)
  - Active account: false
  ✓ Logged in to github.com account octocat (keyring)
  - Active account: true
EOF
exit 0`)

	accounts := gh.GHAccounts(context.Background())
	if len(accounts) != 2 {
		t.Fatalf("read %d accounts, want 2: %+v", len(accounts), accounts)
	}
	if accounts[0].Login != "octocat" || !accounts[0].Active {
		t.Errorf("the active account is not first: %+v", accounts)
	}
	if accounts[1].Active {
		t.Errorf("a second account was marked active: %+v", accounts)
	}

	// And the single-account reader agrees with it, since it is the one the
	// export asks before creating anything.
	active, loggedIn := gh.GHStatus(context.Background())
	if !loggedIn || active.Login != "octocat" {
		t.Errorf("the status named %+v", active)
	}
}

// Signing out and switching both reach a command line with a host and a login on
// it. Both come from gh's own output, which is a reason to expect the check to
// pass, not a reason to skip it.
func TestAnAccountArgvWouldMisreadIsRefused(t *testing.T) {
	gh := fakeGH(t, `exit 0`)
	ctx := context.Background()

	for _, account := range []GHAccount{
		{Host: "", Login: "octocat"},
		{Host: "github.com", Login: ""},
		{Host: "--hostname", Login: "octocat"},
		{Host: "github.com", Login: "-x"},
	} {
		if err := gh.GHSwitch(ctx, account); err == nil {
			t.Errorf("switch accepted %+v", account)
		}
		if err := gh.GHLogout(ctx, account); err == nil {
			t.Errorf("logout accepted %+v", account)
		}
	}
}

// Only the two values gh understands, because this writes a setting every gh on
// the machine then reads.
func TestOnlyARealGitProtocolIsWritten(t *testing.T) {
	recorded := filepath.Join(t.TempDir(), "argv")
	gh := fakeGH(t, `printf '%s\n' "$@" > `+recorded+`; exit 0`)
	ctx := context.Background()

	if err := gh.SetGitProtocol(ctx, "carrier-pigeon"); err == nil {
		t.Error("a protocol gh does not understand was written")
	}
	if _, err := os.Stat(recorded); err == nil {
		t.Error("gh was run anyway")
	}

	if err := gh.SetGitProtocol(ctx, "ssh"); err != nil {
		t.Fatal(err)
	}
	argv, err := os.ReadFile(recorded)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(argv), "git_protocol") || !strings.Contains(string(argv), "ssh") {
		t.Errorf("gh was asked for something else:\n%s", argv)
	}
}

// gh exits 1 for every one of these, so the difference between "pick another
// name" and "your token is missing a scope" is entirely in the text. Each needs
// a different thing from the person reading it.
func TestWhatWentWrongIsTurnedIntoWhatToDo(t *testing.T) {
	tests := []struct {
		name      string
		said      string
		advice    string
		nameTaken bool
		created   bool
	}{
		{
			name:      "the name is taken",
			said:      "GraphQL: Name already exists on this account (createRepository)",
			advice:    "That name is taken",
			nameTaken: true,
		},
		{
			// The one failure where trying again changes the problem rather than
			// repeating it: the repository is already there.
			name:    "created, but the push failed",
			said:    "git@github.com: Permission denied (publickey).\nfailed to push",
			advice:  "The repository was created",
			created: true,
		},
		{
			name:   "the credential was refused",
			said:   "HTTP 401: Bad credentials (https://api.github.com/graphql)",
			advice: "gh auth login",
		},
		{
			name:   "the token is missing a scope",
			said:   "HTTP 403: Resource not accessible by integration",
			advice: "gh auth refresh -s repo",
		},
		{
			name:   "there is no network",
			said:   "dial tcp: lookup api.github.com: no such host",
			advice: "GitHub could not be reached",
		},
		{
			name:   "the owner is not one you can create in",
			said:   "HTTP 404: Not Found (https://api.github.com/orgs/acme)",
			advice: "that owner does not exist",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			gh := fakeGH(t, `echo `+shellSingleQuote(test.said)+` >&2; exit 1`)

			_, err := gh.CreateRepository(context.Background(), t.TempDir(), GHRepo{Name: "estate"})
			if err == nil {
				t.Fatal("a failed create reported success")
			}

			var failure *CreateFailure
			if !errors.As(err, &failure) {
				t.Fatalf("the failure is not readable: %v", err)
			}
			if failure.NameTaken != test.nameTaken {
				t.Errorf("NameTaken is %v", failure.NameTaken)
			}
			if failure.Created != test.created {
				t.Errorf("Created is %v", failure.Created)
			}
			if !strings.Contains(err.Error(), test.advice) {
				t.Errorf("it does not say %q:\n%v", test.advice, err)
			}
			// And what gh said survives in every case: the advice is added to it,
			// never instead of it.
			if !strings.Contains(err.Error(), strings.Split(test.said, "\n")[0]) {
				t.Errorf("what gh said was dropped:\n%v", err)
			}
		})
	}
}

// Output this does not recognize passes through unchanged rather than acquiring
// a guess. gh's own message is usually the better one, and a wrong hint costs
// more than no hint.
func TestAnUnrecognizedFailureGetsNoInventedAdvice(t *testing.T) {
	gh := fakeGH(t, `echo "something nobody has seen before" >&2; exit 1`)

	_, err := gh.CreateRepository(context.Background(), t.TempDir(), GHRepo{Name: "estate"})

	var failure *CreateFailure
	if !errors.As(err, &failure) {
		t.Fatalf("the failure is not readable: %v", err)
	}
	if failure.Advice != "" {
		t.Errorf("it invented advice: %q", failure.Advice)
	}
	if !strings.Contains(err.Error(), "something nobody has seen before") {
		t.Errorf("what gh said was dropped:\n%v", err)
	}
}

// shellSingleQuote renders a value for the fake gh's shell script.
func shellSingleQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

// No description, no flag. gh would take an empty value and set the description
// to nothing, which is a different thing from leaving it alone.
func TestNoDescriptionMeansNoFlag(t *testing.T) {
	recorded := filepath.Join(t.TempDir(), "argv")
	gh := fakeGH(t, `printf '%s\n' "$@" > `+recorded+`; exit 0`)

	if _, err := gh.CreateRepository(context.Background(), t.TempDir(),
		GHRepo{Name: "estate", Description: "   "}); err != nil {
		t.Fatal(err)
	}
	argv, err := os.ReadFile(recorded)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(argv), "--description") {
		t.Errorf("an empty description was passed:\n%s", argv)
	}
}
