name: Go Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/go-release.yml@v1.3.5
    with:
      runner_type: "blacksmith-4vcpu-ubuntu-2404"
      go_version: '1.25'
      goreleaser_distribution: 'goreleaser'
      goreleaser_version: 'latest'
      run_tests_before_release: true
      enable_docker: false
      enable_homebrew: false
      enable_notifications: true
    secrets: inherit
