name: Unit Tests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches: [develop, release-candidate, main]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  unit-tests:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/go-unit-tests.yml@feature/go-workflows
    with:
      enable_matrix: false
      enable_race_detector: true
      enable_coverage: false
      test_timeout: '10m'
