// Package infracli drives the Terraform roots of lerian-terraform-foundation
// from the command line, behind `lerian infra`. It is the terminal face of
// internal/infra; the wizard is the other one, and both walk the same code, so a
// run cannot behave differently depending on which one started it.
//
// It replaced this repository's deploy.sh, whose flags it kept so that anything
// written against the script keeps working. GCP and Azure are not here: they are
// still on the pre-v2 layout, and deploy-legacy.sh is the only thing that reaches
// them.
package infracli

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/lerian-studio/lerian-cli/internal/infra"
	cliversion "github.com/lerian-studio/lerian-cli/internal/version"
)

// version is the CLI version. internal/version is what the goreleaser build
// fills in, so `lerian infra --version` and `lerian version` cannot disagree.
var version = cliversion.Version

// missingBackendNote is what a dry run prints in place of the backend path. A
// dry run reports a missing backend file instead of failing, so it never reaches
// infra.LoadBackend's error — and that error is where the second remediation
// lives: the file is generated by bootstrap, but an environment bootstrapped by
// someone else has the bucket and no file, and then the fix is to write it by
// hand. Naming only bootstrap leaves that operator with an apply that cannot
// succeed, because the bucket already exists.
const missingBackendNote = "MISSING — run --target bootstrap --action apply, " +
	"or write it by hand if this environment was bootstrapped elsewhere " +
	"(see examples/aws/backend/README.md)"

type options struct {
	repo string
	// templatesDir relocates the managed checkout. A read-only home, a network
	// home, or an operator who keeps tooling under XDG all need it somewhere else.
	templatesDir string
	environment  string
	target       string
	action       string
	format       string
	// profile is the AWS profile chosen interactively, and profileChosen records
	// that a choice was made at all.
	//
	// Two fields, for the same reason initOptions carries profileSet: the empty
	// string is an answer — the credentials already in this environment, which have
	// no profile name — and it is indistinguishable from the absence of one. A
	// scripted run leaves both zero and the file decides, exactly as before.
	profile       string
	profileChosen bool

	// account is who the chosen profile resolves to, carried from the account
	// question to the environment one: which environments are available depends on
	// it, since a checkout holds one account per environment.
	account string

	// targetsFromSetup records that init just chose the targets, so the question
	// that would ask for them again is skipped.
	targetsFromSetup bool

	// backends lists the state backends an account holds. It is here so a test can
	// answer the question without credentials; a run leaves it nil and gets the
	// AWS CLI.
	backends              infra.BackendLister
	jobs                  int
	minCredentialLifetime time.Duration
	autoApprove           bool
	dryRun                bool
	list                  bool
	showVersion           bool
}

func run(ctx context.Context, args []string, stdout, stderr io.Writer) error {
	// Subcommands, dispatched before the flag set sees anything. Everything else
	// stays flags-only, so the surface deploy.sh defined is untouched.
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		switch args[0] {
		case "init":
			return runInit(ctx, args[1:], stdout, stderr)
		case "check":
			return runCheck(ctx, args[1:], stdout, stderr)
		case "cleanup", "clean":
			return runCleanup(ctx, args[1:], stdout, stderr)
		}
	}

	var opts options

	flags := flag.NewFlagSet("lerian infra", flag.ContinueOnError)
	flags.SetOutput(stderr)
	flags.Usage = func() { fmt.Fprint(stderr, usage) }

	flags.StringVar(&opts.templatesDir, "templates-dir", "",
		"where the managed checkout lives (default ~/.lerian/lerian-terraform-foundation)")
	flags.StringVar(&opts.repo, "repo", "",
		"path to the lerian-terraform-foundation checkout "+
			"(default: $LERIAN_TF_REPO, else discovered by walking up from the working directory)")
	flags.StringVar(&opts.environment, "env", "", "dev, stg or prd")
	flags.StringVar(&opts.target, "target", "infra-base", "what to operate on")
	flags.StringVar(&opts.action, "action", "plan", "plan, apply, destroy, output or helm-values")
	flags.StringVar(&opts.format, "format", "json", "json or yaml, for --action helm-values")
	flags.IntVar(&opts.jobs, "jobs", 4, "how many services of one product run at once")
	flags.BoolVar(&opts.autoApprove, "auto-approve", false, "skip the confirmation before apply/destroy")
	flags.DurationVar(&opts.minCredentialLifetime, "min-credential-lifetime", 0,
		"refuse to start apply/destroy when the credential has less than this left (e.g. 2h); 0 only warns")
	flags.BoolVar(&opts.dryRun, "dry-run", false, "resolve and print the execution plan, then exit")
	flags.BoolVar(&opts.list, "list", false, "list discoverable targets and exit")
	flags.BoolVar(&opts.showVersion, "version", false, "print the version and exit")

	if err := flags.Parse(args); err != nil {
		return err
	}
	if rest := flags.Args(); len(rest) > 0 {
		// deploy.sh took the provider as a positional argument and redirected
		// azure/gcp to the legacy script. This tool replaces deploy.sh, so it
		// inherits that signpost: examples/gcp and examples/azure are still on
		// the pre-v2 flat layout (no environments, no per-service state) and
		// deploy-legacy.sh remains the only way to reach them.
		switch rest[0] {
		case "azure", "gcp":
			return fmt.Errorf("%q is not handled by this tool\n"+
				"lerian infra is AWS-only: it assumes the v2 layout (one state per\n"+
				"service, environments, backend/<env>.hcl). The GCP and Azure examples\n"+
				"are still on the pre-v2 flat layout and kept their interactive flow:\n\n"+
				"  ./deploy-legacy.sh", rest[0])
		case "aws":
			return fmt.Errorf("this tool does not take a provider as a positional argument\n" +
				"It is AWS-only, and AWS needs an environment:\n\n" +
				"  lerian infra --env dev --target infra-base --action plan")
		}
		return fmt.Errorf("unexpected argument %q\n"+
			"This command takes flags only. Run lerian infra --help.", rest[0])
	}
	if opts.showVersion {
		// The templates floor belongs here: the binary and the templates are two
		// repositories on independent version lines, so "which version" is only
		// answerable with both numbers — and a bug report that omits the templates
		// tag hides the likeliest cause, a checkout older than this binary reads.
		fmt.Fprintf(stdout, "lerian infra %s (templates %s and later)\n", version, infra.TemplatesMinRef)
		return nil
	}

	layout, source, err := resolveLayout(opts.repo, os.Getenv("LERIAN_TF_REPO"), opts.templatesDir)
	if err != nil {
		// Nothing pointed anywhere. With a terminal that is a question, not a
		// failure: the operator knows where the clone is, and telling them to set an
		// environment variable and run again is a round trip for information they
		// could give right now. The answer is written down, so it is asked once per
		// machine rather than once per shell.
		if ask := newPrompter(stderr); ask.interactive && errors.Is(err, errNoCheckoutAnywhere) {
			answered, askErr := obtainCheckout(ctx, ask, stderr, opts.templatesDir)
			if askErr != nil {
				return askErr
			}
			if layout, err = infra.NewLayout(answered); err != nil {
				return err
			}
			source = sourceAsked
		} else {
			return err
		}
	}

	catalog, err := infra.Discover(layout)
	if err != nil {
		return err
	}

	// --list makes no AWS call, reads no config and needs no tools.
	if opts.list {
		printTargets(stdout, layout, catalog)
		return nil
	}

	// Where the command would fail for want of an answer, and there is a terminal
	// to ask, it asks instead. Nothing else changes: --env present means no
	// question, so every invocation that works today behaves exactly as it did,
	// and without a terminal the error below is still what happens.
	terraform, err := prepareChoices(ctx, newPrompter(stderr), catalog, &opts, layout, source, stderr)
	if err != nil {
		return err
	}

	if !infra.ValidEnvironment(opts.environment) {
		if opts.environment == "" {
			return fmt.Errorf("--env is required\n"+
				"One of: %s.\n"+
				"It selects the AWS account (examples/aws/environments.conf), the state backend\n"+
				"(examples/aws/backend/<env>.hcl) and the variables file (envs/<env>.tfvars)\n"+
				"inside every stack.\n"+
				"  lerian infra --env dev --target infra-base --action plan",
				strings.Join(infra.Environments, ", "))
		}
		return fmt.Errorf("invalid --env %q\n"+
			"Valid values: %s. These three are fixed: envs/<env>.tfvars, backend/<env>.hcl and\n"+
			"the bootstrap workspace all key off exactly these names.",
			opts.environment, strings.Join(infra.Environments, ", "))
	}

	action, err := infra.ParseAction(opts.action)
	if err != nil {
		return err
	}
	if opts.format != "json" && opts.format != "yaml" {
		return fmt.Errorf("invalid --format %q\nValid values: json, yaml.", opts.format)
	}
	if opts.jobs < 1 {
		return fmt.Errorf("invalid --jobs %d\nMust be at least 1. Default 4; use 1 to run sequentially.",
			opts.jobs)
	}
	if action == infra.ActionHelmValues {
		if err := requireProductTarget(opts.target); err != nil {
			return err
		}
	}

	// helm-values writes a document to stdout, so `> values.yaml` captures the
	// document and nothing else. Everything else goes to stderr in that mode.
	progressOut := stdout
	if action == infra.ActionHelmValues {
		progressOut = stderr
	}

	// Target resolution is pure filesystem work and reports the most common typo,
	// so it runs before the config is even opened: "unknown product 'ledger'" is a
	// more useful first error than "environments.conf is missing".
	stages, err := infra.Resolve(layout, catalog, opts.target)
	if err != nil {
		return err
	}

	config, err := infra.LoadEnvConfig(layout, opts.environment)
	if err != nil {
		return err
	}
	config = applyChosenProfile(config, opts.profile, opts.profileChosen)

	// The shared tier is opt-in per engine. Dropping the ones this environment never
	// configured is what lets "apply the shared tier" run as one parallel stage
	// instead of refusing because an engine nobody uses has no tfvars.
	var skippedShared []string
	stages, skippedShared = infra.SkipUnconfiguredShared(stages, opts.environment)
	if len(stages) == 0 {
		return fmt.Errorf("target %q resolved to no configured Terraform root\n"+
			"The shared tier is opt-in per engine: run `lerian infra init --env %s "+
			"--targets shared-resources` to configure the ones you want.",
			opts.target, opts.environment)
	}

	if action == infra.ActionDestroy {
		var warnings []infra.BackendWarning
		stages, warnings, err = infra.ForDestroy(stages, opts.target)
		if err != nil {
			return err
		}
		for _, warning := range warnings {
			fmt.Fprintf(stderr, "warn  %s\n", warning)
		}
	}

	allUnits := infra.Units(stages)
	if len(allUnits) == 0 {
		return fmt.Errorf("target %q resolved to no Terraform root\nRun lerian infra --list.", opts.target)
	}

	backend, backendNote, err := loadBackend(layout, config, allUnits, opts.dryRun, stderr)
	if err != nil {
		return err
	}

	// Verified before anything is printed, not after: a preflight block that lists
	// a terraform path it has not resolved yet would have to be interrupted to
	// print it, and that is exactly what used to split the block in half — the
	// path landed below the explanation, and the account line floated loose under
	// it.
	//
	// Both tools are gated together so a machine missing both is told so once.
	// Returning at the first gap sends the operator to install terraform, run
	// again, and only then learn the AWS CLI is v1 — the same round trip
	// 'lerian-infra check' exists to collapse.
	// Already built when the questions were asked; built here otherwise. Either
	// way it happens once, because the probe shells out to the binary.
	if terraform == nil {
		var err error
		if terraform, _, err = preflight(ctx, newPrompter(stderr), stderr, layout, source, opts.dryRun); err != nil {
			return err
		}
	}
	terraform.Profile = config.Profile

	// Resolved once, here, before anything runs in parallel. Four terraform
	// processes starting together each refreshing the same SSO token is a race we
	// created by parallelising, and it surfaces as a credential error that looks
	// like a broken profile.
	if !opts.dryRun {
		credentials, err := infra.ResolveCredentials(ctx, config.Profile)
		if err != nil {
			return err
		}
		terraform.Credentials = credentials

		err = guardCredentialLifetime(
			progressOut, credentials, action, opts.minCredentialLifetime, config.Profile)
		if err != nil {
			return err
		}
	}

	// The account check is part of the preflight, so it is resolved here too and
	// printed as that block's last line. Skipped for a dry run, which makes no AWS
	// call by definition.
	var caller infra.Caller
	if !opts.dryRun {
		caller, err = infra.VerifyAccount(ctx, infra.CLIIdentity{}, config)
		if err != nil {
			return err
		}
	}

	printPreflight(progressOut, layout, config, opts,
		templatesLine(ctx, layout, source), backendNote, terraform.ExecPath(), caller)

	for _, name := range skippedShared {
		// Said out loud, not inferred from an absence: an engine silently missing
		// from a run is how somebody discovers later that it was never applied.
		fmt.Fprintf(progressOut, "  skipping    %s  (not configured for %s)\n", name, opts.environment)
	}

	readiness := checkReadiness(progressOut, action, allUnits, opts.environment)
	explainStages(progressOut, stages, action)

	if opts.dryRun {
		return printDryRun(progressOut, stages, opts, backend, readiness)
	}

	// Offered before refusing: the refusal names the file and the exact lines, so
	// it already knows everything needed to fix them, and somebody is sitting in
	// front of it.
	readiness = fillPendingVarFiles(ctx, newPrompter(progressOut), infra.CLIZones{},
		readiness, opts.environment, config.Profile)

	if err := failOnUnready(readiness); err != nil {
		return err
	}

	// Created, restricted and claimed before it has a name the cleanup looks for,
	// so a cleanup running alongside this one can never see it unclaimed.
	runDir, err := newRunDir()
	if err != nil {
		return err
	}
	// Saved plans can contain values read from state; the logs are kept so a
	// failure can be read after the run.
	defer removePlans(runDir)

	logs := infra.NewFileLogs(runDir)
	defer func() { _ = logs.Close() }()
	terraform.Logs = logs.Writer

	checklist := newChecklist(progressOut, stages)
	runner, err := infra.NewRunner(infra.RunnerOptions{
		Layout:    layout,
		Env:       opts.environment,
		Backend:   backend,
		Terraform: terraform,
		Jobs:      opts.jobs,
		Progress:  checklist,
		RunDir:    runDir,
	})
	if err != nil {
		return err
	}

	// One function for every action, so the menu that follows a run can ask for
	// another one without rebuilding the runner, the logs or the plans.
	perform := func(action infra.Action) error {
		switch action {
		case infra.ActionHelmValues:
			return writeHelmValues(ctx, runner, allUnits, opts.format, stdout)
		case infra.ActionOutput:
			return writeOutputs(ctx, runner, allUnits, stdout)
		default:
			return execute(ctx, runner, stages, action, opts, config, runDir, logs, terraform.Credentials, progressOut)
		}
	}

	if err := perform(action); err != nil {
		return err
	}

	// Resolved after the run, because an apply is what makes the cluster exist and
	// its outputs readable. nil when there is none, which is what keeps the row out
	// of the menu rather than a row that fails when picked.
	ask := newPrompter(progressOut)
	var kubectl func() error
	facts, found, why := readClusterFacts(ctx, terraform, allUnits)
	switch {
	case found:
		kubectl = func() error {
			return pointKubectl(ctx, ask, progressOut, facts, config.Region, config.Profile)
		}
	case why != "":
		// Said rather than silently dropping the row. A long apply can outlive the
		// credential that started it, and an offer that quietly is not there reads
		// as a tool that forgot rather than one that could not.
		fmt.Fprintf(progressOut, "\n  %s\n", newStyle(progressOut).dim(
			"cannot offer to point kubectl at the cluster: "+why))
	}

	// Inside the run, not after it: the saved plans are removed when this function
	// returns, and they are what the detail is read from.
	return afterRun(ctx, ask, runner, terraform, stages, action, progressOut, perform, kubectl)
}

// checkoutSource says which of the four ways of finding a checkout was the one
// that worked. It reaches the preflight, because with more than one possible tree
// "which one is this command reading" stops being obvious.
type checkoutSource string

const (
	sourceFlag       checkoutSource = "--repo"
	sourceEnv        checkoutSource = "$LERIAN_TF_REPO"
	sourceWorkingIn  checkoutSource = "the working directory"
	sourceManaged    checkoutSource = "managed"
	sourceRemembered checkoutSource = "remembered"
	sourceAsked      checkoutSource = "answered just now"
)

// resolveLayout finds the checkout to drive, in this order of precedence:
// an explicit --repo, then $LERIAN_TF_REPO, then a walk up from the working
// directory, and finally the managed checkout this tool creates.
//
// The binary is built from the repository it drives, so the walk is the ordinary
// case and needs no flag: any directory inside the checkout resolves. The flag
// and the variable stay because `go install` puts the binary on $PATH, where it
// can be run from anywhere.
//
// The managed checkout comes LAST on purpose. An operator working inside a
// development checkout must keep driving that one — resolving to the managed tree
// because it also happens to exist would silently run their command against
// different templates than the ones they are editing.
//
// Finding is not creating: only `init` may clone. An `--action apply` that
// downloaded a repository halfway through is a surprise, and the whole point of
// the version pin is that acquiring templates is a deliberate act.
func resolveLayout(flagRepo, envRepo, templatesDir string) (infra.Layout, checkoutSource, error) {
	root, source := flagRepo, sourceFlag
	if root == "" {
		root, source = envRepo, sourceEnv
	}
	if root == "" {
		working, err := os.Getwd()
		if err != nil {
			return infra.Layout{}, "", fmt.Errorf("cannot resolve the working directory: %w", err)
		}
		if found := infra.FindCheckout(working); found != "" {
			root, source = found, sourceWorkingIn
		}
	}
	if root == "" {
		// A recorded answer before the managed path: one is somebody saying which
		// checkout to use, the other is a directory happening to exist at a
		// conventional location. With the convention first, a client who cloned the
		// templates somewhere of their own could not make this use it — the question
		// was never asked, because the managed path had already answered.
		//
		// It still loses to the working directory: standing inside a checkout means
		// that one, whatever was written down on a previous run.
		if remembered := rememberedCheckout(); remembered != "" {
			root, source = remembered, sourceRemembered
		}
	}
	if root == "" {
		// Both locations: the one under ~/.lerian and the one managed checkouts
		// used to go to. A machine that cloned before the move keeps working.
		if managed := infra.FirstManagedCheckout(templatesDir); managed != "" {
			root, source = managed, sourceManaged
		}
	}
	if root == "" {
		working, _ := os.Getwd()
		managed, _ := infra.ManagedCheckoutPath(templatesDir)
		return infra.Layout{}, "", noCheckoutAnywhere(working, managed)
	}

	layout, err := infra.NewLayout(root)
	if err != nil {
		return infra.Layout{}, "", err
	}
	if !infra.IsCheckout(layout.Root) {
		return infra.Layout{}, "", notACheckout(layout.Root, string(source))
	}
	return layout, source, nil
}

// templatesLine describes which tree this command is reading and at which tag.
//
// It replaced a bare "repo <path>" once a second possible tree existed. When a plan
// comes out different from what was expected, "which templates did this actually
// read" is the first question, and it used to be unanswerable from the output.
//
// A checkout that is not on a tag reports "untagged" rather than a guess: claiming a
// version for a branch, or for a commit between tags, is exactly the false assurance
// the version pin exists to remove. Reading the tag costs one git call, and git may
// legitimately be absent — a checkout handed over by --repo works without it — so a
// failure there drops the tag instead of failing the run.
//
// When the checkout is not at the ref this binary declares, the line says which ref
// it expected. This is the one place every command passes through, so it is where a
// mismatch gets noticed by someone who never runs init — and it stays a note on the
// line, not a block, because a plan or a destroy is not the moment to lecture.
func templatesLine(ctx context.Context, layout infra.Layout, source checkoutSource) string {
	line, _ := inspectTemplates(ctx, layout, source)
	return line
}

// inspectTemplates returns the line describing the checkout and the ref it found,
// in one pass. The ref is returned rather than recovered by a second call because
// reading it shells out to git, and the caller that judges the checkout needs the
// same answer the line was built from.
func inspectTemplates(ctx context.Context, layout infra.Layout, source checkoutSource) (string, string) {
	line := layout.Root

	git, err := infra.NewGitCLI()
	if err != nil {
		// No git means no ref to read. The path is still worth reporting, and the
		// checkout is still verifiable by its directories.
		return fmt.Sprintf("%s  (%s)", line, source), ""
	}

	state := infra.InspectCheckout(ctx, git, layout.Root, source == sourceManaged)
	ref := state.Ref
	if ref == "" {
		ref = "untagged"
	}
	line += " @ " + ref
	if infra.RefBelowMin(state.Ref) {
		line += fmt.Sprintf("  (%s)  — older than %s, the oldest this binary reads",
			source, infra.TemplatesMinRef)
		return line, state.Ref
	}
	return fmt.Sprintf("%s  (%s)", line, source), state.Ref
}

// notACheckout is the failure for a path the operator NAMED that turns out not to
// hold a checkout. It names all four ways of pointing at one — including the ones
// they did not use, which is the whole reason this error exists.
func notACheckout(path, source string) error {
	return fmt.Errorf("no lerian-terraform-foundation checkout at %s (resolved from %s)\n"+
		"A checkout is recognized by the directories examples/aws/_modules and\n"+
		"examples/aws/backend; at least one of them is missing there.\n\n"+
		"%s", path, source, pointingOptions())
}

// errNoCheckoutAnywhere marks the ONE failure that cloning can fix: nothing was
// named and nothing was found. A path the operator named that turns out not to hold
// a checkout is a typo, and acquiring a second tree on top of it would bury the
// mistake instead of reporting it — so that failure deliberately does not wrap this.
var errNoCheckoutAnywhere = errors.New("no checkout found")

// noCheckoutAnywhere is the failure when nothing was named and nothing was found.
//
// It lists every place that was looked at WITH the value each one had, because
// "not found" without "here is where I looked" leaves the operator guessing which
// of four mechanisms they got wrong.
func noCheckoutAnywhere(working, managed string) error {
	return fmt.Errorf("%w: no lerian-terraform-foundation checkout found\n\n"+
		"Looked in, in order:\n"+
		"  --repo                             not given\n"+
		"  $LERIAN_TF_REPO                    %s\n"+
		"  the working directory and parents  %s\n"+
		"  the managed checkout               %s\n\n"+
		"%s", errNoCheckoutAnywhere, valueOrUnset(os.Getenv("LERIAN_TF_REPO")),
		working, managed, pointingOptions())
}

func valueOrUnset(value string) string {
	if value == "" {
		return "not set"
	}
	return value
}

// pointingOptions is the remedy shared by both failures, so the two cannot drift
// into naming different sets of options.
func pointingOptions() string {
	return "Point lerian infra at one. In order of precedence:\n" +
		"  1. lerian infra --repo /path/to/lerian-terraform-foundation ...\n" +
		"  2. export LERIAN_TF_REPO=/path/to/lerian-terraform-foundation\n" +
		"  3. run it from inside the checkout — any directory in it will do, the root\n" +
		"     is found by walking up.\n" +
		"  4. lerian infra init --clone — clones the templates matching this binary\n" +
		"     into ~/.lerian/lerian-terraform-foundation and uses that from then on.\n" +
		"     --templates-dir puts the clone somewhere else."
}

// loadBackend reads backend/<env>.hcl and runs the two offline guards. A run made
// entirely of bootstrap does not need it: bootstrap is the stack that writes it.
func loadBackend(
	layout infra.Layout,
	config infra.EnvConfig,
	units []infra.Unit,
	dryRun bool,
	stderr io.Writer,
) (infra.Backend, string, error) {
	needed := false
	for _, unit := range units {
		if !unit.Bootstrap {
			needed = true
			break
		}
	}
	if !needed {
		return infra.Backend{}, "(not needed — bootstrap creates it)", nil
	}

	backend, err := infra.LoadBackend(layout, config.Environment)
	if err != nil {
		// The point of a dry run is to see the whole picture, including what is not
		// ready yet, so a missing backend file is reported rather than fatal.
		if dryRun && errors.Is(err, infra.ErrNoBackendFile) {
			return infra.Backend{}, missingBackendNote, nil
		}
		return infra.Backend{}, "", err
	}

	warnings, err := infra.CheckBackend(layout, config, backend)
	if err != nil {
		return infra.Backend{}, "", err
	}
	for _, warning := range warnings {
		fmt.Fprintf(stderr, "warn  %s\n", warning)
	}
	return backend, backend.Bucket, nil
}

func checkReadiness(out io.Writer, action infra.Action, units []infra.Unit, env string) []infra.Readiness {
	if action == infra.ActionOutput || action == infra.ActionHelmValues {
		// Read-only actions never pass -var-file, so the variables file is irrelevant
		// to them, and demanding it would block reading the outputs of a stack
		// somebody else applied.
		fmt.Fprintf(out, "  tfvars      not required for --action %s\n", action)
		return nil
	}
	return infra.CheckReadiness(units, env)
}

func failOnUnready(readiness []infra.Readiness) error {
	var problems []string
	for _, entry := range readiness {
		if !entry.Ready() {
			problems = append(problems, fmt.Sprintf("  %s: %s\n    %s",
				entry.Unit.Name, entry.Problem, indent(entry.Remediation, "    ")))
		}
	}
	if len(problems) == 0 {
		return nil
	}
	return fmt.Errorf("%d stack(s) are not ready:\n%s\n\n"+
		"Run with --dry-run to see the whole list without stopping at the first one.",
		len(problems), strings.Join(problems, "\n"))
}

func requireProductTarget(target string) error {
	switch {
	case target == "bootstrap", target == "all",
		target == "infra-base", strings.HasPrefix(target, "infra-base/"):
		return fmt.Errorf("--action helm-values needs a product target\n"+
			"%q has no helm_values output; the Helm handoff lives in products/<product>/<service>.\n"+
			"  lerian infra --env dev --target midaz --action helm-values", target)
	}
	return nil
}

func execute(
	ctx context.Context,
	runner *infra.Runner,
	stages []infra.Stage,
	action infra.Action,
	opts options,
	config infra.EnvConfig,
	runDir string,
	logs *infra.FileLogs,
	credentials infra.Credentials,
	out io.Writer,
) error {
	started := time.Now()

	confirm := func(stage infra.Stage, plans []infra.UnitResult) error {
		// Asked again here, not only in the preflight: this runs after the stage
		// was planned and, without --auto-approve, after a human took as long as
		// they took to answer. The session that was long enough to start may not be
		// long enough to write.
		if err := credentialLifetimeError(credentials, action, opts.minCredentialLifetime, config.Profile); err != nil {
			return err
		}
		if opts.autoApprove {
			return nil
		}
		// No table here either: the tree printed each stack's counts as it planned.
		// The question carries the stage total, which is the number being agreed to.
		var create, update, destroy int
		for _, plan := range plans {
			create += plan.Changes.Create
			update += plan.Changes.Update
			destroy += plan.Changes.Delete
		}
		verb := "Apply"
		if action == infra.ActionDestroy {
			verb = "DESTROY"
		}
		// Three short lines rather than one long one. What is being changed, where
		// it lands, and the question — in that order, because the account is the
		// fact worth re-reading before typing yes, and it was previously trailing a
		// parenthesis at the end of a line already past column eighty.
		theme := newStyle(out)
		fmt.Fprintf(out, "  %s %s\n", theme.bold(verb), theme.bold(stage.Name))
		fmt.Fprintf(out, "    %s\n", changeSummary(create, update, destroy))
		fmt.Fprintf(out, "    %s\n\n", destinationLine(config))

		return confirmOnStdin(ctx, out, "  type yes to continue · ctrl-c cancels: ")
	}
	if action == infra.ActionPlan {
		confirm = nil
	}

	results, err := runner.Execute(ctx, stages, action, confirm)

	// No per-stage table here. The tree above already reported every stack's
	// counts as it finished; repeating them in a one-row table per stage said the
	// same thing twice and buried the one number an operator actually acts on.
	for _, result := range results {
		if result.Blocked {
			fmt.Fprintf(out, "\n  [%s] not planned — needs %s applied first\n",
				result.Stage.Name, result.BlockedBy)
		}
	}

	if err != nil {
		printFailureLogs(out, results, logs)
		fmt.Fprintf(out, "\n  logs %s\n", runDir)

		// The detail was just printed, in full, next to the stack it belongs to.
		// Returning the wrapped error would make main print the same Terraform
		// output a second time — the operator scrolls past one copy to find the
		// other and neither says anything the first did not. Aborting is passed
		// through untouched: callers test for it, and it carries no detail to
		// duplicate.
		if errors.Is(err, infra.ErrAborted) {
			return err
		}
		return reported{summary: summarize(err)}
	}

	printClusterHandoff(ctx, out, runner, results, action, config)

	fmt.Fprintf(out, "\n%s\n", newStyle(out).bold(totalsLine(results, action, time.Since(started))))
	fmt.Fprintf(out, "  logs %s\n\n", runDir)

	if action == infra.ActionPlan {
		if infra.Blocked(results) {
			// Not an error, and the exit code says so. A first run cannot plan past
			// the first layer, because every layer resolves the one below it in AWS
			// and a plan sees only what AWS already has.
			fmt.Fprintf(out,
				"  Nothing was changed. The stages above the first are not planned yet: each one\n"+
					"  resolves resources the stage below creates, and a plan only sees what already\n"+
					"  exists in AWS.\n\n"+
					"  Apply builds them in order, planning each stage after the one below it is up:\n\n"+
					"    lerian infra --env %s --target %s --action apply\n\n",
				config.Environment, opts.target)
			return nil
		}
		fmt.Fprint(out, "  Nothing was changed. Re-run with --action apply to execute this plan.\n\n")
	}
	return nil
}

func writeHelmValues(
	ctx context.Context,
	runner *infra.Runner,
	units []infra.Unit,
	format string,
	stdout io.Writer,
) error {
	document, err := runner.HelmValues(ctx, units)
	if err != nil {
		return err
	}

	var rendered []byte
	if format == "yaml" {
		rendered, err = document.YAML()
	} else {
		rendered, err = document.JSON()
	}
	if err != nil {
		return err
	}
	_, err = stdout.Write(rendered)
	return err
}

func writeOutputs(ctx context.Context, runner *infra.Runner, units []infra.Unit, stdout io.Writer) error {
	outputs, err := runner.Outputs(ctx, units)
	if err != nil {
		return err
	}
	for _, unit := range units {
		values := outputs[unit.Name]
		fmt.Fprintf(stdout, "\n%s\n", newStyle(stdout).bold("==> "+unit.Name))
		names := make([]string, 0, len(values))
		for name := range values {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			fmt.Fprintf(stdout, "  %s = %s\n", name, values[name])
		}
	}
	return nil
}

// confirmOnStdin asks once, and only accepts the whole word.
func confirmOnStdin(ctx context.Context, out io.Writer, prompt string) error {
	// A real isatty, not a character-device check: /dev/null is a character device
	// too, and a CI run redirecting stdin from it would be mistaken for a human.
	if !isTerminal(os.Stdin) {
		return fmt.Errorf("this run needs a confirmation but stdin is not a terminal\n"+
			"Pending: %s\n\n"+
			"Re-run from a terminal, or pass --auto-approve. The plan above is what would be\n"+
			"applied: --auto-approve does not re-plan, it applies exactly the saved plan files\n"+
			"that produced that table.", prompt)
	}

	// Only what is typed after the question counts as the answer. Stages here take
	// minutes, and anything pressed while waiting is still queued when the prompt
	// finally appears.
	reader, err := drain()
	if err != nil {
		return fmt.Errorf("cannot make sure the confirmation is answered deliberately: %w\n"+
			"Re-run with --auto-approve if you mean to skip it.", err)
	}
	if reader == nil {
		reader = bufio.NewReader(os.Stdin)
	}

	fmt.Fprint(out, prompt)
	answer, err := readLineOrCancel(ctx, reader)
	if errors.Is(err, infra.ErrAborted) {
		fmt.Fprintln(out)
		return infra.ErrAborted
	}
	if err != nil && !errors.Is(err, io.EOF) {
		return fmt.Errorf("cannot read the confirmation: %w", err)
	}
	if strings.TrimSpace(answer) != "yes" {
		return infra.ErrAborted
	}
	return nil
}

func printFailureLogs(out io.Writer, results []infra.StageResult, logs *infra.FileLogs) {
	for _, result := range results {
		for _, phase := range [][]infra.UnitResult{result.Plans, result.Applies} {
			for _, unit := range phase {
				if unit.Err == nil {
					continue
				}
				fmt.Fprintf(out, "\n---- %s failed ----\n%s\n  full log: %s\n",
					unit.Unit.Name, indent(unit.Err.Error(), "  "), logs.Path(unit.Unit))
			}
		}
	}
}

// guardCredentialLifetime says out loud how long the run's credentials have, and
// refuses to start a write when that is less than the operator demanded.
//
// The credentials are resolved ONCE for the whole run — see credentials.go for the
// SSO cache race that forces it — so whatever is left at this moment is all the run
// gets. An apply that outlives it is not a clean failure: AWS finishes the change,
// the state write loses its credential, the lock stays held by a dead process and
// an errored.tfstate is left in the root. Recovery is force-unlock plus state push,
// by hand, on a root that may be a money path.
//
// Only apply and destroy are gated. A plan is short and writes no state, so
// blocking one because a session expires in twenty minutes would cost more than it
// protects. And a session with no expiry is not a session at risk: nothing is said.
func guardCredentialLifetime(
	out io.Writer,
	credentials infra.Credentials,
	action infra.Action,
	floor time.Duration,
	profile string,
) error {
	if err := credentialLifetimeError(credentials, action, floor, profile); err != nil {
		return err
	}
	left, known := credentials.RemainingLifetime(time.Now())
	if !known || (action != infra.ActionApply && action != infra.ActionDestroy) {
		return nil
	}
	fmt.Fprintf(out, "  credential  %s left%s\n", roundLifetime(left), lifetimeNote(left, floor))
	return nil
}

// credentialLifetimeError is the check on its own, so it can run again at the
// moment of each write without printing the preflight line a second time.
//
// Checking once before planning is not enough: planning a large target and then
// waiting for a human to type yes can burn most of a session, and later stages of
// the same run start later still. The refusal has to be asked the question again
// right before each stage that writes.
func credentialLifetimeError(
	credentials infra.Credentials,
	action infra.Action,
	floor time.Duration,
	profile string,
) error {
	if floor <= 0 {
		return nil
	}
	if action != infra.ActionApply && action != infra.ActionDestroy {
		return nil
	}
	left, known := credentials.RemainingLifetime(time.Now())
	if !known || left >= floor {
		return nil
	}
	return fmt.Errorf("the credential has %s left, less than the %s this run requires\n"+
		"The credentials are resolved once for the whole run, so an apply that\n"+
		"outlives them loses the state write while AWS finishes the change.\n\n"+
		"Refresh the session and start again. %s",
		roundLifetime(left), roundLifetime(floor), refreshHint(profile))
}

// refreshHint names the command for the profile in hand rather than assuming one.
// "aws sso login" is right only for an IAM Identity Center profile; an assume-role
// or credential_process profile refreshes another way, and a run that names the
// wrong command sends the operator down a path that cannot work.
func refreshHint(profile string) string {
	if profile == "" {
		return "How depends on how the profile is configured:\n" +
			"  IAM Identity Center:  aws sso login --profile <profile>\n" +
			"  anything else:        re-run whatever issues the session for it"
	}
	return fmt.Sprintf("How depends on how %q is configured:\n"+
		"  IAM Identity Center:  aws sso login --profile %s\n"+
		"  anything else:        re-run whatever issues the session for it",
		profile, profile)
}

// lifetimeNote nudges when nothing was demanded and the session is short anyway.
// Without --min-credential-lifetime nothing refuses, so the only thing left to do
// is make the number impossible to miss.
func lifetimeNote(left, floor time.Duration) string {
	if floor > 0 || left >= time.Hour {
		return ""
	}
	return "  (short — a long apply may outlive it; see --min-credential-lifetime)"
}

// roundLifetime prints a duration the way an operator reads a clock, not the way
// Go prints nanoseconds.
func roundLifetime(d time.Duration) string {
	if d < 0 {
		return "0s"
	}
	if d >= time.Hour {
		return d.Round(time.Minute).String()
	}
	return d.Round(time.Second).String()
}

// printPreflight writes the whole block at once. Every value it names is already
// resolved by the time it is called, which is what keeps it from being split.
func printPreflight(
	out io.Writer,
	layout infra.Layout,
	config infra.EnvConfig,
	opts options,
	templates, backend, terraformPath string,
	caller infra.Caller,
) {
	theme := newStyle(out)
	fmt.Fprintf(out, "\n%s\n", theme.bold("==> Preflight"))
	fmt.Fprintf(out, "  templates   %s\n", templates)
	fmt.Fprintf(out, "  environment %s\n", config.Environment)
	fmt.Fprintf(out, "  account     %s  (declared in %s)\n",
		config.AccountID, layout.RepoRel(layout.ConfigFile()))
	fmt.Fprintf(out, "  profile     %s\n", profileLabel(config.Profile))
	fmt.Fprintf(out, "  region      %s\n", config.Region)
	fmt.Fprintf(out, "  backend     %s\n", backend)
	fmt.Fprintf(out, "  target      %s\n", opts.target)
	fmt.Fprintf(out, "  action      %s\n", opts.action)
	fmt.Fprintf(out, "  terraform   %s\n", terraformPath)

	if caller.Account == "" {
		return
	}
	// The credentials really do reach the declared account. Printed as the block's
	// closing line rather than floating on its own, because it is the verification
	// of everything listed above it.
	fmt.Fprintf(out, "  verified    %s\n", caller.ARN)
}

func printDryRun(
	out io.Writer,
	stages []infra.Stage,
	opts options,
	backend infra.Backend,
	readiness []infra.Readiness,
) error {
	problems := map[string]infra.Readiness{}
	for _, entry := range readiness {
		if !entry.Ready() {
			problems[entry.Unit.Name] = entry
		}
	}

	fmt.Fprintf(out, "\n%s\n", newStyle(out).bold("==> Execution plan (dry run — no AWS call was made)"))
	for i, stage := range stages {
		fmt.Fprintf(out, "\n  stage %d: %s\n", i+1, stage.Name)
		if len(stage.Units) > 1 && opts.jobs > 1 {
			fmt.Fprintf(out, "    (%d units, up to %d in parallel)\n", len(stage.Units), opts.jobs)
		}
		for _, unit := range stage.Units {
			if unit.Bootstrap {
				fmt.Fprintf(out, "      %-44s local state, workspace=%s\n",
					unit.Name, opts.environment)
			} else {
				fmt.Fprintf(out, "      %-44s %s\n", unit.Name, unit.StateKey())
			}
			if problem, ok := problems[unit.Name]; ok {
				fmt.Fprintf(out, "        NOT READY: %s\n", problem.Problem)
			}
		}
	}

	// An empty path has two very different causes, and saying "bootstrap only" for
	// both told a fresh checkout that it needed no backend when in fact its backend
	// file had not been generated yet.
	backendPath := backend.Path
	if backendPath == "" {
		backendPath = "<none: bootstrap only>"
		for _, stage := range stages {
			for _, unit := range stage.Units {
				if !unit.Bootstrap {
					backendPath = missingBackendNote
					break
				}
			}
		}
	}
	fmt.Fprintf(out, "\n  backend-config  %s\n", backendPath)
	fmt.Fprintf(out, "  var-file        <stack>/envs/%s.tfvars\n", opts.environment)
	fmt.Fprintf(out, "  init flags      -reconfigure -input=false  (bootstrap: workspace select/new)\n\n")

	if len(problems) > 0 {
		return fmt.Errorf("%d of %d stack(s) are NOT READY — see the NOT READY lines above.\n"+
			"A missing envs/%s.tfvars is copied from the *.tfvars-example next to it; a\n"+
			"placeholder is a <...> token that still needs a real value.",
			len(problems), len(readiness), opts.environment)
	}
	fmt.Fprintf(out, "  ok  all %d stack(s) ready\n\n", len(readiness))
	return nil
}

// guidedRun fills in the run's three choices when none were given.
//
// It is reached only where the command would otherwise fail: --env is the one
// flag with no default, so an invocation that passes it never gets here, and
// every command that works today behaves exactly as it did. Without a terminal
// this returns untouched and the caller falls through to the error that names the
// flag — which is what keeps the command usable from CI.
//
// Target and action are asked in the same breath rather than left at their
// defaults, because an operator who did not know to pass --env did not choose
// "infra-base" and "plan" either. They are offered preselected, so three Enters
// reproduce exactly the old default run.
//
// The questions go to stderr: the action is one of the things being chosen, and
// helm-values needs stdout to carry nothing but the document.
// afterAccount is called as soon as the account is chosen, with the profile that
// was picked. Its error stops the remaining questions.
//
// It exists for one check: an expired credential makes every later answer
// worthless. The profile is what it needs, not the environment — the credential
// belongs to the profile, and which environment the account is deployed as is
// still three questions away at that point.
func guidedRun(
	ctx context.Context,
	catalog infra.Catalog,
	opts *options,
	ask *prompter,
	layout infra.Layout,
	resolved []infra.ResolvedProfile,
	afterAccount func(profile string, chosen bool) error,
) error {
	if !ask.interactive {
		return nil
	}

	// A list of steps rather than three calls in a row, so r can walk back through
	// them. The questions are a sequence and a wrong turn on the first one used to
	// cost the whole run: the only way to correct it was ctrl-c, which throws away
	// the answers that were right along with the one that was not.
	//
	// Each step reports whether it actually asked anything. A step that decided
	// without a question must be invisible to r — going back to it would land on a
	// screen that is not there, return immediately, and move forward again, so the
	// key would appear to do nothing.
	steps := []func() (bool, error){
		func() (bool, error) {
			return askAccountStep(ctx, ask, catalog, layout, resolved, opts, afterAccount)
		},
		func() (bool, error) { return askEnvironmentStep(ctx, ask, catalog, layout, opts) },
		func() (bool, error) { return askTargetStep(ctx, ask, catalog, layout, opts) },
		func() (bool, error) { return askActionStep(ask, opts) },
	}
	asked := make([]bool, len(steps))

	for at := 0; at < len(steps); {
		answered, err := steps[at]()
		asked[at] = answered
		switch {
		case errors.Is(err, errBack):
			back := previousQuestion(asked, at)
			if back < 0 {
				// Nothing before the first question, so back out of the run — which is
				// where the operator came from.
				return infra.ErrAborted
			}
			at = back
		case err != nil:
			return err
		default:
			at++
		}
	}
	return nil
}

// previousQuestion is the last step before at that put a question on screen, or
// -1 when there is none.
func previousQuestion(asked []bool, at int) int {
	for back := at - 1; back >= 0; back-- {
		if asked[back] {
			return back
		}
	}
	return -1
}

func askAccountStep(
	ctx context.Context,
	ask *prompter,
	catalog infra.Catalog,
	layout infra.Layout,
	resolved []infra.ResolvedProfile,
	opts *options,
	afterAccount func(profile string, chosen bool) error,
) (bool, error) {
	choice, err := askForAccount(ctx, ask, ask.out, catalog, layout, resolved)
	if err != nil {
		return false, err
	}
	opts.environment = choice.environment
	opts.profile = choice.profile
	opts.account = choice.account
	opts.profileChosen = choice.chosen

	if afterAccount != nil {
		return true, afterAccount(choice.profile, choice.chosen)
	}
	return true, nil
}

// askAboutBackend settles what the state backend is, by asking the account
// rather than inferring it from a file that may simply never have been written
// in this checkout.
//
// Called from inside the targets step rather than standing as a step of its own.
// It needs the account, and it changes the list that follows — with a backend
// adopted, every target becomes runnable instead of one. As a separate step it
// would also swallow r whenever it had nothing to ask: a step that returns
// without a question cannot tell "going back" from "done", so the cursor would
// bounce off it and never reach the account question.
// backendLister is the AWS CLI unless a caller supplied something else.
func (o *options) backendLister() infra.BackendLister {
	if o.backends != nil {
		return o.backends
	}
	return infra.CLIBackends{}
}

func askAboutBackend(ctx context.Context, ask *prompter, layout infra.Layout, opts *options) error {
	if backendExists(layout, opts.environment) {
		return nil
	}
	// Nobody to answer means nothing to do with the answer. Adopting a backend is
	// a decision, so without a terminal the scan would spend an AWS call to print
	// something no one asked for — in CI, on every run.
	if !ask.interactive {
		return nil
	}

	// The account comes from environments.conf rather than from the credentials:
	// it is the account this environment is ALLOWED to touch, and the bucket name
	// is built from it. A mismatch between the two is a separate guard's job, and
	// it runs before anything is applied.
	config, err := infra.LoadEnvConfig(layout, opts.environment)
	//nolint:nilerr // There is no account to look a bucket up for, so the question
	// has no subject and is skipped. The error is not swallowed: every path that
	// needs this config loads it again and reports it properly. Returning it here
	// would turn a missing environments.conf into a failure at the one question
	// that exists only to offer a shortcut.
	if err != nil {
		return nil
	}

	return resolveBackend(ctx, ask, ask.out, opts.backendLister(), layout,
		opts.environment, opts.profile, config.Region, config.AccountID)
}

// askEnvironmentStep asks which environment the chosen account is deployed as,
// and sets it up when that is the first time.
//
// A step of its own because an account is not an environment. Deriving one from
// the other meant an account could only ever be one: a sandbox configured as dev
// could never also be stg in the same checkout, because the lookup found dev and
// stopped. It is also where the sizing is decided, and that is not a thing to
// inherit from whichever section happened to name this account first.
func askEnvironmentStep(
	ctx context.Context,
	ask *prompter,
	catalog infra.Catalog,
	layout infra.Layout,
	opts *options,
) (bool, error) {
	// The dry-run path already asked, from the file, because that is all it can
	// read. Nothing to do here.
	if opts.environment != "" {
		return false, nil
	}

	choices := environmentChoices(layout, opts.account)
	if firstEnabled(choices) < 0 || !choices[firstEnabled(choices)].selectable() {
		return false, errCheckoutFull(layout, opts.account)
	}

	chosen, err := ask.pick(
		"Which environment is this account?",
		"It picks the sizing the templates ship, and the state backend to use.",
		"--env", choices, "")
	if err != nil {
		return false, err
	}
	opts.environment = chosen

	// Already configured for this account: the files are there and the run can go
	// straight on to what to operate on.
	if config, loadErr := infra.LoadEnvConfig(layout, chosen); loadErr == nil && config.AccountID == opts.account {
		return true, nil
	}

	if err := setUpEnvironment(ctx, ask.out, layout, opts); err != nil {
		return true, err
	}
	// What init just wrote variables for is the answer to the targets question, so
	// that question does not get asked.
	if configured := configuredTargets(catalog, layout, chosen); len(configured) > 0 {
		opts.target = strings.Join(configured, ",")
		opts.targetsFromSetup = true
	}
	return true, nil
}

func askTargetStep(
	ctx context.Context,
	ask *prompter,
	catalog infra.Catalog,
	layout infra.Layout,
	opts *options,
) (bool, error) {
	if err := askAboutBackend(ctx, ask, layout, opts); err != nil {
		return false, err
	}

	// Already decided by the setup that just ran. Said rather than asked, because
	// the answer is on screen two questions up and asking for it again is the
	// duplicate this removes.
	if opts.targetsFromSetup {
		fmt.Fprintf(ask.out, "\n%s\n  %s\n\n", newStyle(ask.out).bold("==> Target"),
			opts.target+"  "+newStyle(ask.out).dim("— what you just configured"))
		return false, nil
	}
	// Preselected from the disk rather than from memory: whatever this environment
	// has tfvars for is what somebody just configured, and it stays true on the
	// runs after this one too.
	preset := splitList(opts.target)
	if len(preset) == 0 {
		preset = configuredTargets(catalog, layout, opts.environment)
	}

	targets, err := ask.pickMany(
		"What do you want to operate on?",
		"Written already — this is what to run now. Several can be combined.",
		"--target", runTargetOptions(catalog, layout, opts.environment), preset)
	if err != nil {
		return false, err
	}
	if len(targets) > 0 {
		opts.target = strings.Join(targets, ",")
	}
	return true, nil
}

func askActionStep(ask *prompter, opts *options) (bool, error) {
	action, err := ask.pick(
		"What should it do?",
		"plan changes nothing. apply and destroy ask for a confirmation before writing.",
		"--action", actionOptions(), opts.action)
	if err != nil {
		return false, err
	}
	opts.action = action
	return true, nil
}

// askForAccount asks which account to deploy into and returns the environment it
// maps to.
//
// The environment is derived rather than asked for: it names the state backend
// and the variables file, so the run needs it, but it is our vocabulary and not
// the operator's. What they are deciding is the account.
// accountChoice is what the account question produced.
//
// chosen is not "profile is non-empty": an empty profile is an answer when the
// ambient-credentials row was picked, and it is the absence of one when the dry-run
// path asked from the file instead. Only the code that asked can tell those apart,
// so it says which.
type accountChoice struct {
	// environment is set only on the dry-run path, where the file is the only
	// thing that can be read and the question is which section to use. Every other
	// path leaves it empty: which environment an account is deployed as is a
	// question of its own, asked after this one.
	environment string
	profile     string
	// account is who the chosen profile resolves to. It is what decides which
	// environments are available, since a checkout holds one account per
	// environment.
	account string
	chosen  bool
}

func askForAccount(
	ctx context.Context,
	ask *prompter,
	out io.Writer,
	catalog infra.Catalog,
	layout infra.Layout,
	resolved []infra.ResolvedProfile,
) (accountChoice, error) {
	// No resolved profiles means nobody asked AWS who anybody is — a dry run, which
	// makes no AWS call by definition. What it can still know is what the file says,
	// so the question is built from the sections instead of from identities.
	if len(resolved) == 0 {
		// Nothing was resolved, so no profile was chosen either: the file decides.
		environment, err := askFromConfig(ask, layout)
		return accountChoice{environment: environment}, err
	}

	choices := accountOptions(layout, resolved)

	profile, err := ask.pick(
		"Which AWS account?",
		"Everything is created there. The state backend and the sizing follow from it.",
		"", choices, "")
	if err != nil {
		return accountChoice{}, err
	}

	if profile == signOutChoice {
		return signOutAndBackIn(ctx, ask, out, catalog, layout, resolved)
	}

	picked := findProfile(resolved, profile)
	if picked == nil {
		return accountChoice{}, fmt.Errorf("profile %q is not one of the profiles offered", profile)
	}

	// A profile with no session yet is chosen precisely to log into it. The login
	// is for that profile's session, not for whichever one came first in the list.
	if !picked.Usable() {
		// Unless there is no session to revive. A profile that lives only in
		// ~/.aws/credentials is an access key, and `aws sso login --profile x` is a
		// command that cannot work for it — what it needs is the key replaced, and
		// what is useful is whatever AWS just said about it.
		if picked.Profile.SSOSession == "" && picked.Profile.Source == "credentials" {
			return accountChoice{}, fmt.Errorf("profile %q does not work: %w\n"+
				"It is an access key in ~/.aws/credentials, with no SSO session to renew.\n"+
				"Replace it:\n\n  aws configure --profile %s",
				picked.Profile.Name, picked.Err, picked.Profile.Name)
		}

		target := infra.SSOTarget{Session: picked.Profile.SSOSession, Profile: picked.Profile.Name}
		if _, loginErr := offerLogin(ctx, ask, out, []infra.SSOTarget{target}); loginErr != nil {
			return accountChoice{}, loginErr
		}

		// Ask again who it is now. The account is what maps to an environment, and
		// before the login there was none to read.
		refreshed, identityErr := checkIdentity.CallerIdentity(ctx, picked.Profile.Name, picked.Profile.Region)
		if identityErr != nil {
			return accountChoice{}, fmt.Errorf("profile %q still does not resolve: %w\n  aws sso login --profile %s",
				profile, identityErr, profile)
		}
		picked.Caller = refreshed
	}

	// Which environment this account is deployed as is the next question, not this
	// one's to answer. Deriving it from the account meant an account could only
	// ever be one environment: a sandbox configured as dev could never be set up
	// as stg in the same checkout, because the lookup found dev and stopped.
	return accountChoice{profile: picked.Profile.Name, account: picked.Caller.Account, chosen: true}, nil
}

// runInitCommand is a variable so the chaining can be exercised without writing
// into a checkout.
var runInitCommand = runInit

// configureAccount sets up the chosen account and returns the slot it went into.
//
// The environment name is bookkeeping, not a decision: backend/<env>.hcl and
// envs/<env>.tfvars are files in the templates repo, one set per name, so an
// account has to occupy one of them. Which one does not matter to whoever is
// deploying, so it is not asked — the first free slot is used.
//
// There are three names, and that is a real ceiling: a checkout already holding
// three accounts cannot take a fourth. Better said here than discovered later as
// a missing file.
// setUpEnvironment runs init for an account that has no section for this
// environment yet.
//
// Telling somebody to leave and run a second command — and to know which of
// three names to give it — is asking them to do the part this already knows how
// to do.
func setUpEnvironment(
	ctx context.Context,
	out io.Writer,
	layout infra.Layout,
	opts *options,
) error {
	theme := newStyle(out)
	fmt.Fprintf(out, "\n%s\n", theme.bold("==> Setting up "+opts.environment+" in account "+opts.account))
	fmt.Fprintf(out, "  %s\n", theme.dim("first time for this pair in this checkout"))

	// No --region. init asks for it, always, and the profile's own region is the
	// suggestion it offers — passing it here would answer the question on somebody's
	// behalf, and where every resource is created is not a thing to inherit from a
	// profile they may have configured for something else.
	args := []string{
		"--env", opts.environment,
		"--profile", opts.profile,
		"--account", opts.account,
	}
	if err := runInitCommand(ctx, args, out, out); err != nil {
		return err
	}

	// Read back rather than assumed: init is what decides what was written, and a
	// run against a section that is not there fails later with a missing file.
	if _, err := infra.LoadEnvConfig(layout, opts.environment); err != nil {
		return fmt.Errorf("account %s was not set up as %s: %w", opts.account, opts.environment, err)
	}
	return nil
}

// applyChosenProfile puts the interactively chosen profile into the configuration
// the run uses.
//
// The environment is found by account, and a section may name a different profile
// reaching the same one — so without this, choosing the profile that works could
// still run as the profile the file names, which may be the expired one. The
// account is untouched: it is what the guard checks, and it is why the two
// profiles were interchangeable in the first place.
//
// chosen false means nothing was picked — a scripted run — and the file stands.
// An empty profile with chosen true is an answer in its own right: the credentials
// already in this environment, which is what CI has and what somebody with an
// exported key has, and neither of them has a profile name.
func applyChosenProfile(config infra.EnvConfig, profile string, chosen bool) infra.EnvConfig {
	if !chosen {
		return config
	}
	config.Profile = profile
	return config
}

// destinationLine is where a write is about to land, for the line read last
// before typing yes.
//
// The region is there because an apply into the right account and the wrong
// region does not fail — it creates a second copy of everything, somewhere nobody
// is looking.
func destinationLine(config infra.EnvConfig) string {
	line := config.Environment + " · account " + config.AccountID
	if config.Region != "" {
		line += " · " + config.Region
	}
	return line
}

// destinationRegion is the region half of where a row lands, ready to append.
func destinationRegion(layout infra.Layout, environment string) string {
	config, err := infra.LoadEnvConfig(layout, environment)
	if err != nil || config.Region == "" {
		return ""
	}
	return "  ·  " + config.Region
}

// nameTheAmbiguous adds the environment to rows that would otherwise read the
// same.
//
// Two environments in one account and one region is a real configuration — a dev
// and a staging sharing a sandbox — and there the name is the only thing telling
// the rows apart, so it earns its place. Everywhere else it is bookkeeping, and
// bookkeeping in a menu is noise the reader has to learn to ignore.
func nameTheAmbiguous(options []option) {
	seen := map[string]int{}
	for _, opt := range options {
		if opt.environment != "" {
			seen[opt.note]++
		}
	}
	for index, opt := range options {
		if opt.environment != "" && seen[opt.note] > 1 {
			options[index].note = opt.note + "  ·  " + opt.environment
		}
	}
}

// environmentForProfile finds the environment whose section names this account,
// preferring one that also names this profile.
//
// The account is what decides it, because the account is what the guard checks.
// The profile breaks a tie: two environments in one account is a real
// configuration — a dev and a staging sharing a sandbox — and then the profile is
// what tells them apart.
func environmentForProfile(layout infra.Layout, profile, account string) (string, bool) {
	var byAccount string

	for _, name := range infra.Environments {
		config, err := infra.LoadEnvConfig(layout, name)
		if err != nil || config.AccountID != account {
			continue
		}
		if config.Profile == profile {
			return name, true
		}
		if byAccount == "" {
			byAccount = name
		}
	}
	return byAccount, byAccount != ""
}

// askFromConfig asks which account using only what environments.conf declares.
//
// It is the dry-run path: no credentials were resolved, so no row can say whether
// a profile still works — but the accounts are written down, and choosing between
// them needs nothing from AWS.
func askFromConfig(ask *prompter, layout infra.Layout) (string, error) {
	choices := make([]option, 0, len(infra.Environments))
	for _, name := range infra.Environments {
		config, err := infra.LoadEnvConfig(layout, name)
		if err != nil {
			continue
		}
		// The section key is dev, stg or prd, and that is bookkeeping: the row reads
		// as the destination it is. The value stays the environment, because that is
		// what the rest of the run needs.
		label := config.Profile
		if label == "" {
			label = "credentials in this environment"
		}

		note := "account " + config.AccountID
		if config.Region != "" {
			note += "  ·  " + config.Region
		}
		choices = append(choices, option{value: name, label: label, note: note, environment: name})
	}
	nameTheAmbiguous(choices)

	if len(choices) == 0 {
		return "", fmt.Errorf("no account is configured in this checkout\n" +
			"examples/aws/environments.conf declares the account, profile and region to\n" +
			"deploy into, and it has no section this tool can use.\n\n" +
			"  lerian infra init")
	}

	return ask.pick(
		"Which AWS account?",
		"Read from environments.conf; a dry run makes no AWS call to check them.",
		"--env", choices, "")
}

// signOutChoice is the row that ends the SSO session and starts a new one.
const signOutChoice = "\x00sign-out"

// ssoLogout is a variable for the same reason ssoLogin is: so the choice can be
// exercised without ending anybody's real session.
var ssoLogout = infra.SSOLogout

// signOutAndBackIn ends the session, logs in again, and re-reads who the profiles
// resolve as.
//
// This is the only way to arrive as a different identity: the profiles in ~/.aws
// are fixed, and which accounts they reach is decided by whoever is signed in. It
// is a row rather than something the command does on its own, because the token
// it clears lives in ~/.aws/sso/cache and every AWS client on the machine reads
// it — another terminal, Terraform, anything on the shared config.
func signOutAndBackIn(
	ctx context.Context,
	ask *prompter,
	out io.Writer,
	catalog infra.Catalog,
	layout infra.Layout,
	resolved []infra.ResolvedProfile,
) (accountChoice, error) {
	if err := ssoLogout(ctx, os.Stdin, out, out); err != nil {
		return accountChoice{}, err
	}
	fmt.Fprintf(out, "\n  %s\n", newStyle(out).dim("signed out"))

	targets := sessionsOf(resolved)
	if len(targets) == 0 {
		return accountChoice{}, fmt.Errorf("no SSO session in ~/.aws to sign in to\n  aws configure sso")
	}
	if _, err := offerLogin(ctx, ask, out, targets); err != nil {
		return accountChoice{}, err
	}

	// Who everything resolves as has just changed, so nothing read before this is
	// still true.
	refreshed := infra.ResolveProfiles(ctx, checkIdentity, profilesOf(resolved), "")
	return askForAccount(ctx, ask, out, catalog, layout, refreshed)
}

// sessionsOf is every SSO session the known profiles sit behind, first seen
// first.
func sessionsOf(resolved []infra.ResolvedProfile) []infra.SSOTarget {
	seen := map[string]bool{}
	targets := make([]infra.SSOTarget, 0, len(resolved))

	for _, entry := range resolved {
		session := entry.Profile.SSOSession
		if session == "" || seen[session] {
			continue
		}
		seen[session] = true
		targets = append(targets, infra.SSOTarget{Session: session})
	}
	return targets
}

func profilesOf(resolved []infra.ResolvedProfile) []infra.AWSProfile {
	profiles := make([]infra.AWSProfile, 0, len(resolved))
	for _, entry := range resolved {
		profiles = append(profiles, entry.Profile)
	}
	return profiles
}

func findProfile(resolved []infra.ResolvedProfile, name string) *infra.ResolvedProfile {
	for index := range resolved {
		if resolved[index].Profile.Name == name {
			return &resolved[index]
		}
	}
	return nil
}

// accountOptions is the question a run actually asks: which AWS account.
//
// dev, stg and prd are names of files in the templates repo — backend/<env>.hcl
// holds the state, envs/<env>.tfvars holds the sizing — so they cannot be removed
// from the model. They can stop being the question. The account is what is being
// decided, it is what the guard checks before anything runs, and it is the thing
// that belongs to the operator rather than to us.
//
// Every profile in ~/.aws gets a row:
//
//   - one reaching a configured account is choosable, and the environment it maps
//     to is shown as a consequence rather than asked for;
//   - one reaching an account with no section cannot be deployed into — there is
//     no state backend and no variables file for it — so the row says how to
//     create one instead of offering a choice that fails two questions later;
//   - one whose session has expired is choosable, because choosing it is how an
//     operator says "log me into that one".
func accountOptions(layout infra.Layout, resolved []infra.ResolvedProfile) []option {
	// Ordered by what can be done with the row, because the cursor starts on the
	// first one: a list that opens on something unusable makes the most likely
	// keypress a mistake. Ready first, then the ones a login would revive, then the
	// ones nothing can be done about from here.
	const (
		ready = iota
		needsLogin
		unconfigured
	)

	type row struct {
		option option
		rank   int
	}

	rows := make([]row, 0, len(resolved))
	for _, entry := range resolved {
		// Credentials in the environment have no profile name. A row labeled with
		// an empty string is a row nobody can read, so they are named for what they
		// are — and CI, or anyone who exported a key, has nothing else to be called.
		label := entry.Profile.Name
		if label == "" {
			label = "credentials in this environment"
		}

		opt := option{value: entry.Profile.Name, label: label}
		rank := ready

		switch {
		case !entry.Usable() && entry.Profile.CanSignIn:
			rank = needsLogin
			opt.note = "session expired — choose to log in"
		case !entry.Usable() && entry.Profile.Source == "credentials":
			// An access key that does not work. Choosing it reports what AWS said,
			// which is more use than a login that cannot apply to it.
			rank = needsLogin
			opt.note = "the access key does not work — choose it to see why"
		case !entry.Usable():
			// Nothing to revive and nothing to fix: ~/.aws commonly holds a [default]
			// with a region and nothing else. Calling that an expired session sends
			// somebody to a login that fails with "Unable to locate credentials",
			// which names neither the problem nor the fix.
			rank = unconfigured
			opt.disabled = true
			opt.note = "no credentials configured — aws configure --profile " + entry.Profile.Name
		default:
			if environment, ok := environmentForProfile(layout, entry.Profile.Name, entry.Caller.Account); ok {
				// The account and the region, which is the whole of what is being
				// decided: an account is a place and so is a region, and naming one
				// without the other describes half of where the resources land.
				//
				// Not the environment. dev, stg and prd pick backend/<env>.hcl and
				// envs/<env>.tfvars, which matters to this tool and to nobody choosing
				// where to deploy. It is added below, and only where two rows would
				// otherwise read identically.
				opt.note = "account " + entry.Caller.Account + destinationRegion(layout, environment)
				opt.environment = environment
			} else {
				rank = unconfigured
				opt.note = "account " + entry.Caller.Account + "  ·  not set up here yet — choosing it sets it up"
			}
		}
		rows = append(rows, row{option: opt, rank: rank})
	}

	sort.SliceStable(rows, func(i, j int) bool { return rows[i].rank < rows[j].rank })

	options := make([]option, 0, len(rows)+1)
	for _, r := range rows {
		options = append(options, r.option)
	}
	nameTheAmbiguous(options)

	// Last, because it is the answer to a different question — not "which of these"
	// but "none of these". Offered only where there is a session to end.
	if len(sessionsOf(resolved)) > 0 {
		options = append(options, option{
			value: signOutChoice,
			label: "sign in as someone else",
			note:  "ends the session for every AWS tool on this machine, then logs in again",
		})
	}
	return options
}

// runTargetOptions is the catalog --list prints, plus the two targets that are
// not products: bootstrap, which creates the state backend, and all.
func runTargetOptions(catalog infra.Catalog, layout infra.Layout, environment string) []option {
	options := make([]option, 0, 3+len(catalog.Names))
	options = append(options,
		option{value: "bootstrap", label: "bootstrap", note: "state bucket and lock table"},
		option{value: "infra-base", label: "infra-base", note: "the VPC then the cluster"},
	)
	for _, name := range catalog.Names {
		options = append(options, option{
			value: name,
			label: name,
			note:  strings.Join(catalog.Products[name], " "),
		})
	}
	options = append(options, option{value: "all", label: "all", note: "everything, in dependency order"})

	// A target whose tfvars were never written cannot run either, and that is a
	// different gap with a different answer: init writes them, and it writes them
	// for the targets it is given. The catalog lists every product; a checkout
	// usually has variables for one or two.
	//
	// Said rather than disabled, because choosing it is how it gets configured —
	// the same as an account that is not set up yet.
	configured := map[string]bool{}
	for index, opt := range options {
		if opt.value == "bootstrap" || opt.value == "all" {
			continue
		}
		if targetIsConfigured(layout, catalog, opt.value, environment) {
			configured[opt.value] = true
			continue
		}
		options[index].note = opt.note + "  ·  not configured here yet"
	}

	// The configured ones first. This question arrives right after `init` wrote
	// the tfvars for one or two targets, and finding them on row 14 of 30 reads as
	// the same list being asked again rather than as the short answer it is.
	//
	// Stable, so the catalog's order survives inside each group and the list does
	// not reshuffle between runs.
	sort.SliceStable(options, func(i, j int) bool {
		return rankTarget(options[i], configured) < rankTarget(options[j], configured)
	})

	// Everything except bootstrap needs somewhere to keep its state, and bootstrap
	// is what creates it — so on an account nobody has bootstrapped yet, it is the
	// only thing that can run. Offering the rest lets somebody spend two answers on
	// a stack that fails at terraform init, reporting a bucket that does not exist.
	//
	// And when the backend IS there, bootstrap is the one row with nothing to do.
	// Leaving it selectable invites a run whose entire output is "no changes", and
	// the question somebody actually has — is my state backend set up? — is
	// answered by the row saying so.
	if backendExists(layout, environment) {
		for index, opt := range options {
			if opt.value == "bootstrap" {
				options[index].disabled = true
				options[index].note = "already there — " + backendName(layout, environment)
			}
		}
		return options
	}
	for index, opt := range options {
		if opt.value == "bootstrap" {
			// Selectable, not fixed: a fixed row is excluded from the answer, and
			// with every other row disabled the answer would come back empty. The
			// note carries what the state is instead.
			options[index].note = "the state backend — the only thing that can run yet"
			continue
		}
		options[index].disabled = true
		options[index].note = "needs the state backend — run bootstrap first"
	}
	return options
}

// targetIsConfigured reports whether every root behind a target has its variables
// for this environment.
//
// The same check the run makes before it starts — a missing envs/<env>.tfvars is
// what "NOT READY" means — asked early enough to put on the row rather than three
// answers later.
func targetIsConfigured(layout infra.Layout, catalog infra.Catalog, target, environment string) bool {
	stages, err := infra.Resolve(layout, catalog, target)
	if err != nil {
		// Not resolvable is a different problem, and the run reports it properly.
		return true
	}
	for _, readiness := range infra.CheckReadiness(infra.Units(stages), environment) {
		if !readiness.Ready() {
			return false
		}
	}
	return true
}

// configuredTargets is what this environment already has variables for, which is
// the answer to "what do you want to operate on" on nearly every run: the targets
// somebody configured are the targets they came here to deploy.
func configuredTargets(catalog infra.Catalog, layout infra.Layout, environment string) []string {
	var ready []string
	for _, name := range append([]string{"infra-base"}, catalog.Names...) {
		if targetIsConfigured(layout, catalog, name, environment) {
			ready = append(ready, name)
		}
	}
	return ready
}

// rankTarget groups the target list: the fixed rows keep their place, then
// anything this environment has variables for, then the rest.
func rankTarget(opt option, configured map[string]bool) int {
	switch {
	case opt.value == "bootstrap":
		return 0
	case opt.value == "infra-base":
		return 1
	case configured[opt.value]:
		return 2
	case opt.value == "all":
		return 4
	default:
		return 3
	}
}

// backendName is the bucket this environment keeps its state in, for a row that
// has to say why there is nothing to create.
func backendName(layout infra.Layout, environment string) string {
	backend, err := infra.LoadBackend(layout, environment)
	if err != nil || backend.Bucket == "" {
		return "the state backend is configured"
	}
	return backend.Bucket
}

// backendExists reports whether this environment has a state backend to write to.
//
// The file is written by bootstrap, not by init: bootstrap creates the bucket and
// the lock table and then records where they are. Its absence is what "nobody has
// bootstrapped this account yet" looks like from here.
func backendExists(layout infra.Layout, environment string) bool {
	_, err := infra.LoadBackend(layout, environment)
	return err == nil
}

// actionOptions spells out the consequence of each action, which is the part an
// operator needs before choosing rather than after.
func actionOptions() []option {
	return []option{
		{value: string(infra.ActionPlan), label: "plan", note: "changes nothing"},
		{value: string(infra.ActionApply), label: "apply", note: "writes, after one confirmation"},
		{value: string(infra.ActionDestroy), label: "destroy", note: "removes, after one confirmation"},
		{value: string(infra.ActionOutput), label: "output", note: "reads terraform output"},
		{value: string(infra.ActionHelmValues), label: "helm-values", note: "merges helm_values onto stdout"},
	}
}

func printTargets(out io.Writer, layout infra.Layout, catalog infra.Catalog) {
	fmt.Fprintf(out, "Discovered targets  (from %s/*/*/main.tf)\n\n",
		layout.RepoRel(layout.ProductsDir()))
	fmt.Fprint(out, "  bootstrap\n  infra-base            infra-base/vpc  infra-base/eks\n  all\n\nProducts\n")

	writer := tabwriter.NewWriter(out, 0, 0, 2, ' ', 0)
	for _, name := range catalog.Names {
		fmt.Fprintf(writer, "  %s\t%s\n", name, strings.Join(catalog.Products[name], " "))
	}
	_ = writer.Flush()
}

func removePlans(runDir string) {
	entries, err := os.ReadDir(runDir)
	if err != nil {
		return
	}
	for _, entry := range entries {
		if strings.HasSuffix(entry.Name(), ".tfplan") {
			_ = os.Remove(filepath.Join(runDir, entry.Name()))
		}
	}
}

func indent(text, prefix string) string {
	lines := strings.Split(text, "\n")
	for i := 1; i < len(lines); i++ {
		lines[i] = prefix + lines[i]
	}
	return strings.Join(lines, "\n")
}

func profileLabel(profile string) string {
	if profile == "" {
		return "<ambient credentials>"
	}
	return profile
}

// totalsLine is the one number an operator acts on, in Terraform's own vocabulary
// and in the tense of what happened.
//
// It sums the plan counts, not the apply counts, because applying a saved plan
// performs exactly what that plan described — and for a plan run there is nothing
// else to sum.
func totalsLine(results []infra.StageResult, action infra.Action, elapsed time.Duration) string {
	var create, update, destroy, stacks, blocked int
	for _, result := range results {
		if result.Blocked {
			blocked += len(result.Stage.Units)
			continue
		}
		for _, plan := range result.Plans {
			if plan.Err != nil {
				continue
			}
			stacks++
			create += plan.Changes.Create
			update += plan.Changes.Update
			destroy += plan.Changes.Delete
		}
	}

	verbs := []string{"to add", "to change", "to destroy"}
	if action != infra.ActionPlan {
		verbs = []string{"added", "changed", "destroyed"}
	}

	line := fmt.Sprintf("  %d %s, %d %s, %d %s across %d stack(s) in %s",
		create, verbs[0], update, verbs[1], destroy, verbs[2], stacks, roundDuration(elapsed))
	if blocked > 0 {
		line += fmt.Sprintf("\n  %d stack(s) not planned yet", blocked)
	}
	return line
}

// roundDuration keeps the total readable: seconds below a minute, whole minutes
// above it. A 41-minute run reported to the second is noise.
func roundDuration(d time.Duration) time.Duration {
	if d < time.Minute {
		return d.Round(time.Second)
	}
	return d.Round(time.Minute)
}

// changeSummary is the counts with the zeros left in, unlike the per-stack lines.
//
// A stack line is one of six being scanned, so the zeros are noise there. This
// line is read once, deliberately, before authorizing a spend — and "0 to destroy"
// is exactly the reassurance an operator wants stated rather than inferred from
// its absence.
func changeSummary(create, update, destroy int) string {
	return fmt.Sprintf("%d to add, %d to change, %d to destroy", create, update, destroy)
}

// explainStages says, in one short paragraph per stage, what is about to be built
// and why it comes first.
//
// The operator running this is frequently meeting Terraform for the first time.
// "target bootstrap, action apply" describes the command, not the intent; without
// the intent there is no way to tell a step that is supposed to take fifteen
// minutes from one that has hung, or a resource worth its cost from one created by
// accident.
func explainStages(out io.Writer, stages []infra.Stage, action infra.Action) {
	if action != infra.ActionApply {
		return
	}
	notes := map[string]string{
		"bootstrap": "Terraform has to record what it created somewhere durable, and that " +
			"store has to exist before anything else. This creates the S3 bucket that holds " +
			"the state and the DynamoDB table that locks it so two people cannot apply at " +
			"once. It also writes backend/<env>.hcl, which every later command reads. " +
			"Runs once per environment, costs cents.",
		"infra-base/vpc": "The network everything else is placed into: subnets across three " +
			"availability zones, split into public, private and database tiers. Every " +
			"datastore later finds its subnets by the tags set here.",
		"infra-base/eks": "The Kubernetes cluster the products run on. The slowest step by " +
			"far — the control plane alone takes around fifteen minutes, then the nodes " +
			"join and the add-ons install.",
	}

	var lines []string
	for _, stage := range stages {
		if note, ok := notes[stage.Name]; ok {
			lines = append(lines, fmt.Sprintf("  %s\n%s\n",
				newStyle(out).bold(stage.Name), wrapIndent(note, "    ", 76)))
			continue
		}
		if stage.Name == "shared-resources" {
			lines = append(lines, fmt.Sprintf("  %s\n%s\n", newStyle(out).bold(stage.Name),
				wrapIndent("The datastores every product in shared mode will resolve. "+
					"They must exist before any product that points at them.", "    ", 76)))
			continue
		}
		lines = append(lines, fmt.Sprintf("  %s\n%s\n", newStyle(out).bold(stage.Name),
			wrapIndent(fmt.Sprintf("The datastores for %s. In dedicated mode they are created here; "+
				"in shared mode this creates nothing and resolves the shared tier instead.",
				stage.Name), "    ", 76)))
	}
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(out, "\n%s\n\n", newStyle(out).bold("==> What this will do"))
	for _, line := range lines {
		fmt.Fprint(out, line)
	}
}

// wrapIndent breaks text at width and indents every line, so a paragraph stays
// readable in an eighty-column terminal.
func wrapIndent(text, indent string, width int) string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return ""
	}
	var out strings.Builder
	line := indent
	for _, word := range words {
		if len(line)+len(word)+1 > width && line != indent {
			out.WriteString(line + "\n")
			line = indent
		}
		if line != indent {
			line += " "
		}
		line += word
	}
	out.WriteString(line)
	return out.String()
}

// printClusterHandoff tells the operator how to reach the cluster that was just
// created.
//
// A finished EKS apply leaves a cluster nothing on the machine can talk to yet:
// kubectl reads ~/.kube/config, and Terraform does not write it. Ending the run
// with "57 added" and nothing else made the next step a search — for the right AWS
// CLI verb, the cluster's exact name, and which profile it lives under, all of
// which this run already knows.
//
// The name is read from the stack's own output rather than derived from the naming
// contract, so a cluster whose name was overridden is still reported correctly.
func printClusterHandoff(
	ctx context.Context,
	out io.Writer,
	runner *infra.Runner,
	results []infra.StageResult,
	action infra.Action,
	config infra.EnvConfig,
) {
	if action != infra.ActionApply {
		return
	}

	var eks *infra.Unit
	for _, result := range results {
		if result.Blocked || len(result.Applies) == 0 {
			continue
		}
		for i, applied := range result.Applies {
			if applied.Err == nil && applied.Unit.Name == "infra-base/eks" {
				eks = &result.Applies[i].Unit
			}
		}
	}
	if eks == nil {
		return
	}

	outputs, err := runner.Outputs(ctx, []infra.Unit{*eks})
	if err != nil {
		// Not worth failing a successful apply over: the cluster is up either way,
		// and the operator can read the name from the console.
		return
	}
	name := ""
	if raw, ok := outputs[eks.Name]["cluster_name"]; ok {
		_ = json.Unmarshal(raw, &name)
	}
	if name == "" {
		return
	}

	profile := ""
	if config.Profile != "" {
		profile = " --profile " + config.Profile
	}

	theme := newStyle(out)
	fmt.Fprintf(out, "\n%s\n\n", theme.bold("==> Reaching the cluster"))
	fmt.Fprint(out, wrapIndent(
		"The cluster is up, but nothing on this machine can talk to it yet: kubectl "+
			"reads ~/.kube/config and Terraform does not write it. This adds the "+
			"context and makes it current:", "  ", 78)+"\n\n")
	fmt.Fprintf(out, "    aws eks update-kubeconfig --name %s --region %s%s\n\n",
		name, config.Region, profile)
	fmt.Fprint(out, wrapIndent("Then confirm the nodes have joined:", "  ", 78)+"\n\n")
	fmt.Fprintf(out, "    kubectl get nodes\n\n")
	fmt.Fprint(out, wrapIndent(
		"An empty list right after the apply is normal for a minute or two while the "+
			"nodes register.", "  ", 78)+"\n\n")

	// The likeliest reason kubectl hangs, and the one whose symptom explains
	// nothing: a timeout, not a refusal. Only the allow-listed address reaches the
	// API at all, and a home connection changes address often enough that the
	// address answered during init is frequently already stale.
	fmt.Fprint(out, wrapIndent(
		"If it times out instead — no error, just a hang — the API is refusing your "+
			"current address. Only "+strings.Join(allowedCIDRs(outputs[eks.Name]), ", ")+
			" can reach it. Compare it with:", "  ", 78)+"\n\n")
	fmt.Fprintf(out, "    curl -s https://checkip.amazonaws.com\n\n")
	fmt.Fprint(out, wrapIndent(
		"and if it moved, update allowed_api_access_cidrs in "+
			"examples/aws/infra-base/eks/envs/"+config.Environment+".tfvars and re-apply "+
			"infra-base/eks. A changed egress address is the usual cause, not a broken "+
			"cluster.", "  ", 78)+"\n")
}

// allowedCIDRs reads the API allow-list the cluster was applied with, so the
// handoff can name the actual address instead of describing the concept.
func allowedCIDRs(outputs map[string]json.RawMessage) []string {
	raw, ok := outputs["allowed_api_access_cidrs"]
	if !ok {
		return []string{"the address allowed at apply time"}
	}
	var cidrs []string
	if err := json.Unmarshal(raw, &cidrs); err != nil || len(cidrs) == 0 {
		return []string{"the address allowed at apply time"}
	}
	return cidrs
}

// reported is an error whose detail has already been shown to the operator.
//
// main prints what it is given, so an error that has been reported in place has to
// arrive short or it arrives twice.
type reported struct{ summary string }

func (r reported) Error() string { return r.summary }

// summarize keeps the first line of a Terraform failure, which names what broke,
// and drops the body that was already printed above.
func summarize(err error) string {
	line := firstLine(err.Error())
	// The wrapped chain ends in the raw terraform output; the part before the last
	// ": " is this package's own explanation, which is the useful half. Both
	// branches used to return the whole line, so the documented trim never happened.
	if index := strings.LastIndex(line, ": "); index > 0 && index < len(line)-2 {
		return line[:index]
	}
	return line
}

// prepareChoices asks for whatever the run needs and was not given, verifying
// the tools first when it is going to ask.
//
// Everything the questions lead to ends in terraform and the AWS CLI, so asking
// before checking spends three answers and then reports a missing tool where it
// reads as a problem with the choices rather than with the machine.
//
// The check is skipped when there is nobody to ask. Without a terminal nothing
// is collected, so there are no answers to protect, and the argument and
// configuration errors that follow are both cheaper to produce and more specific
// than "terraform is missing": a script with a bad --target should hear about
// the target.
//
// The CLI it builds is returned rather than rebuilt later, because the probe
// shells out to the terraform binary.
func prepareChoices(
	ctx context.Context,
	ask *prompter,
	catalog infra.Catalog,
	opts *options,
	layout infra.Layout,
	source checkoutSource,
	stderr io.Writer,
) (*infra.CLI, error) {
	if opts.environment != "" {
		return nil, nil
	}

	var (
		terraform *infra.CLI
		profiles  []infra.ResolvedProfile
	)
	if ask.interactive {
		var err error
		terraform, profiles, err = preflight(ctx, newPrompter(stderr), stderr, layout, source, opts.dryRun)
		if err != nil {
			return nil, err
		}
	}
	checkCredential := credentialCheck(ctx, layout, opts.dryRun)
	if err := guidedRun(ctx, catalog, opts, ask, layout, profiles, checkCredential); err != nil {
		return nil, err
	}
	return terraform, nil
}

// credentialCheck resolves the profile the chosen environment maps to and asks
// whether it still answers. A nil result means there is nothing to check — a dry
// run makes no AWS call by definition.
func credentialCheck(
	ctx context.Context,
	layout infra.Layout,
	dryRun bool,
) func(profile string, chosen bool) error {
	if dryRun {
		return nil
	}
	return func(profile string, chosen bool) error {
		resolve := credentialProfile(layout, "", profile, chosen)
		if resolve == "" {
			return nil
		}
		_, err := infra.ResolveCredentials(ctx, resolve)
		return err
	}
}

// credentialProfile is the profile the early check resolves: the one that was
// chosen, or the section's own when nothing was.
//
// Split out because the decision is the part worth testing — resolving it runs
// the AWS CLI.
//
// Empty means there is nothing for this check to resolve, which happens two ways
// and neither is its failure to report: the configuration could not be read, and
// that error has its own message further down written for the case where it is
// the only problem; or the credentials are ambient, and whether they work is
// answered by the account guard a moment later.
func credentialProfile(layout infra.Layout, environment, profile string, chosen bool) string {
	// A chosen profile is the one the run will use whatever any section says, and
	// at the point this runs there may be no environment yet: which one an account
	// is deployed as is a later question. Reading the config here would return
	// nothing and skip the check entirely — the check whose whole purpose is to
	// fail before three more questions are answered.
	if chosen {
		return profile
	}
	config, err := infra.LoadEnvConfig(layout, environment)
	if err != nil {
		return ""
	}
	return applyChosenProfile(config, profile, chosen).Profile
}
