package infracli

// usage is written by hand rather than generated by the flag package: the flags of
// this command need paragraphs, not one-line descriptions, because most of them
// select which AWS account gets touched.
const usage = `lerian infra — deploy the AWS v2 stacks of lerian-terraform-foundation

USAGE
  lerian infra check                                   verify this machine
  lerian infra init --env <dev|stg|prd> [flags]        write the configuration
  lerian infra --env <dev|stg|prd> [--target <target>] [--action <action>] [options]

FIRST RUN
  Before anything else, 'lerian infra check' reports the dependencies this tool
  shells out to and the checkout it would use, in one pass and without touching
  AWS. A run verifies the same things, but each one only when it is first needed,
  so a bare machine is fixed over as many rounds as it has gaps.

  A fresh checkout has no configuration: environments.conf and every
  envs/<env>.tfvars are gitignored, because they carry an AWS account id. The init
  subcommand writes them, asking for what it cannot discover:

    lerian infra init --env dev

  It lists the AWS profiles it found with the account each one reaches, detects
  this machine's egress address for the cluster's API allow-list, and materializes
  one tfvars per root from the committed *.tfvars-example next to it. Nothing it
  does touches an AWS resource. Run 'lerian infra init --help' for its flags —
  every question it asks has one, so CI never has to answer a prompt.

RUNNING IT WITHOUT FLAGS
  In a terminal, "lerian infra" with no --env asks instead of failing: environment,
  target and action, chosen with the arrow keys. Target accepts several, toggled
  with space; q cancels. Everything else about the run is unchanged, so three Enters are
  exactly --env <the first> --target infra-base --action plan.

  Passing --env skips all of it. A command that works today behaves identically,
  and outside a terminal nothing is ever asked — the flag is named in an error, as
  it always was, which is what keeps this usable from CI.

  The same lists appear in init for --env, --targets, --mode and --profile. The
  profile list carries the account each one reaches, because that is the real
  question; a profile whose session expired is shown greyed out rather than hidden,
  so a missing account explains itself.

  The confirmation before an apply or a destroy is deliberately NOT a list: it
  still wants the word "yes" typed. Enter is exactly the key that gets left in the
  input queue during a long stage, and that prompt exists to not be answered by
  accident.

FLAGS
  --repo <path>           The lerian-terraform-foundation checkout to drive.
                          Rarely needed: running the command anywhere inside a
                          checkout is enough, and a binary installed from the
                          releases page finds the managed checkout on its own.
                          Resolution order:
                            1. --repo
                            2. $LERIAN_TF_REPO
                            3. walk up from the working directory until a
                               directory holding examples/aws/_modules and
                               examples/aws/backend is found.
                            4. the managed checkout, ~/.lerian/lerian-terraform-foundation
                          The managed checkout is LAST on purpose: an operator
                          working inside a development checkout must keep driving
                          that one, not the managed tree that also happens to
                          exist. Only init may create it — a run that downloaded
                          a repository halfway through would be a surprise.

  --templates-dir <path>  Where the managed checkout lives, when not the default.

  --profile <name>        init only, and NOT a flag of a run: a run reads the
                          profile for --env out of examples/aws/environments.conf,
                          which init wrote. What both need is the AWS CLI, installed
                          AND configured — it is what turns a profile into
                          credentials, whether that profile uses IAM Identity Center
                          (aws configure sso) or an access key and secret
                          (aws configure). One profile per account, so normally one
                          per environment.

  --clone / --no-clone    init only. Whether a missing checkout may be downloaded
                          into the managed path. --clone needs --templates-ref;
                          --no-clone fails instead. In a terminal, neither is a
                          question; outside one, a missing checkout with neither
                          flag is an error, because a CI run must never fetch a
                          repository by accident. --auto-approve does not imply
                          --clone.

  --templates-ref <tag>   init only. The lerian-terraform-foundation tag to clone
                          or sync to. No default: which templates release to run is
                          yours to choose, and this binary pins nothing. It does
                          refuse anything below the floor it was built against;
                          lerian infra --version prints it.

  --env <dev|stg|prd>     REQUIRED. Selects the AWS account from
                          examples/aws/environments.conf, the backend file
                          examples/aws/backend/<env>.hcl, and the variables file
                          envs/<env>.tfvars inside every stack.

  --target <target>       What to operate on. Default: infra-base.
                            bootstrap                state bucket + lock table
                            infra-base               vpc then eks
                            infra-base/vpc           just the VPC
                            infra-base/eks           just the cluster
                            shared-resources         the whole shared datastore tier
                            shared-resources/<svc>   one shared datastore
                            <product>                every service of one product
                            <product>/<service>      one service
                            all                      everything, in order
                          Several targets can be combined with commas:
                            --target infra-base,midaz
                          The parts are reordered into dependency order, so
                          "midaz,infra-base" and "infra-base,midaz" run the same
                          way and neither can put a datastore before its VPC.
                          Products and services are DISCOVERED from
                          examples/aws/products/*/*/main.tf. A new product works
                          the moment its directory exists. Run --list to see them.

  --action <action>       Default: plan.
                            plan          terraform plan only. Changes nothing.
                            apply         plan, show the summary, confirm, apply.
                            destroy       the same, for -destroy plans.
                            output        terraform output for every unit.

  --auto-approve          Skip the single confirmation before apply/destroy.
                          Terraform still applies a saved plan file, so what runs
                          is exactly what was shown.

  --min-credential-lifetime <d>
                          Refuse to START an apply or a destroy when the credential
                          has less than this left, e.g. 2h. Default 0: the lifetime
                          is printed in the preflight and nothing is refused.

                          It exists because the credentials are resolved ONCE for
                          the whole run — every Terraform process gets the same
                          keys, which is what keeps four of them from fighting over
                          the SSO cache. Whatever lifetime was left when the run
                          started is all it has. An apply that outlives it does not
                          fail cleanly: AWS finishes the change, the state write
                          loses its credential, the lock stays held by a dead
                          process, and an errored.tfstate is left in the root.
                          Recovery is force-unlock and state push, by hand.

                          A plan is never refused: it is short and writes no state.

                          The check runs in the preflight AND again immediately
                          before each stage that writes, because planning a large
                          target and waiting for a confirmation can burn most of a
                          session.

  --jobs <n>              Services inside one product run in parallel. Default 4.
                          Ordered stages (bootstrap, vpc, eks) are always
                          sequential regardless of this.

  --dry-run               Resolve and print the execution plan — units, order,
                          state keys, backend file, profile, expected account —
                          then exit. Makes NO AWS call at all.

  --list                  List discoverable targets and exit. Makes no AWS call,
                          reads no configuration.

  --version               Print the version and exit.
  --help                  This text.

THE ACCOUNT GUARD
  Three checks run before anything else, and two of them cost no AWS call. A
  --dry-run makes no AWS call at all, so it runs the first two and skips the third:

    1. the state bucket in backend/<env>.hcl ends in -<account_id>, which catches
       a backend file left over from another account;
    2. the region in environments.conf matches the one in backend/<env>.hcl;
    3. aws sts get-caller-identity resolves to the declared account_id.

  There is deliberately no flag to bypass any of them, and --auto-approve does not
  skip them. If the account genuinely changed, edit environments.conf — a
  reviewable, diffable act — instead of typing an override at the end of a long
  day.

THE SHARED TIER IS OPT-IN PER ENGINE
  shared-resources holds five engines because five exist in AWS, not because any
  environment wants all five. An engine with no envs/<env>.tfvars is skipped and
  reported by name, so "apply the shared tier" is not refused because of a
  datastore nobody uses — MSK, whose floor is three brokers, being the usual one.

  For a PRODUCT this does not apply: every datastore under it is required by its
  chart, so a missing tfvars there stays an error.

  S3 is never shared, and that is why the tier has no s3 root. A bucket holds one
  application's objects under one policy, one lifecycle and one key, so the roots
  that own one — br-sfn, fetcher, plugin-bc-correios, reporter — carry no mode
  switch. Shared mode leaves them alone: they still create a real bucket, and they
  still need to be applied along with the product.

ORDER
  apply    bootstrap -> infra-base/vpc -> infra-base/eks
                     -> shared-resources/* -> products/*
  destroy  the exact reverse.

  bootstrap is never destroyed: the bucket and the lock table carry
  prevent_destroy = true. See examples/aws/bootstrap/README.md, "Teardown".

WHY -reconfigure IS ALWAYS PASSED
  .terraform/ caches the resolved backend, including the bucket of whichever
  environment was initialized last. Without -reconfigure, switching environments
  in the same checkout keeps the stale bucket and the run dies with a 403 at apply
  time — long after the plan looked fine. Every init here passes it.

ENVIRONMENT VARIABLES
  LERIAN_TF_REPO      The checkout to drive, when not running inside one.
  LERIAN_TEMPLATES_REPO
                      Where init --clone clones from, for an air-gapped client
                      with an internal mirror or an organization that vendors the
                      templates into its own git server.
  NO_COLOR            Set to anything to disable bold and color. Color is also
                      off automatically when the output is not a terminal, so a
                      redirected file or a CI log never contains escape codes.
  LERIAN_SELECT       plain falls back from the arrow-key lists to the typed
                      prompts, for a terminal that cannot be switched to raw mode
                      or renders the list badly. A terminal that refuses raw mode
                      falls back on its own, without this.
  LERIAN_SPINNER      ascii falls back from the braille progress spinner to
                      | / - \, for a terminal or font that renders braille as
                      empty boxes.

EXAMPLES
  lerian infra init --env dev
  lerian infra --list
  lerian infra --env dev --target all --dry-run
  lerian infra --env dev --target bootstrap --action apply
  lerian infra --env stg --target infra-base/vpc --action plan
  lerian infra --env prd --target midaz --action apply --jobs 4
  lerian infra --env dev --target midaz/postgres --action destroy

  A whole environment on shared datastores, from an empty account:
    lerian infra init --env dev                       # answer: shared
    lerian infra --env dev --target bootstrap        --action apply
    lerian infra --env dev --target infra-base       --action apply
    lerian infra --env dev --target shared-resources --action apply
    lerian infra --env dev --target midaz            --action apply
`
